/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddelivery;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vasanth
 */
public class Anbagam_Mess extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant_Anjappar
     */
    public Anbagam_Mess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        Idly = new javax.swing.JCheckBox();
        Poori = new javax.swing.JCheckBox();
        Chappathi = new javax.swing.JCheckBox();
        Dosa = new javax.swing.JCheckBox();
        Pongal = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IdlyQuantity = new javax.swing.JSpinner();
        PooriQuantity = new javax.swing.JSpinner();
        ChappathiQuantity = new javax.swing.JSpinner();
        DosaQuantity = new javax.swing.JSpinner();
        PongalQuantity = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ChickenBiriyani = new javax.swing.JCheckBox();
        MuttonBiriyani = new javax.swing.JCheckBox();
        VegMeals = new javax.swing.JCheckBox();
        NonVegMeals = new javax.swing.JCheckBox();
        GrilledChicken = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        ChickenBiriyaniQuantity = new javax.swing.JSpinner();
        MuttonBiriyaniQuantity = new javax.swing.JSpinner();
        VegMealsQuantity = new javax.swing.JSpinner();
        NonVegMealsQuantity = new javax.swing.JSpinner();
        GrilledChickenQuantity = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        ParottaSet = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        ChickenFriedRice = new javax.swing.JCheckBox();
        Oothappam = new javax.swing.JCheckBox();
        MuttonDosa = new javax.swing.JCheckBox();
        SilonParotta = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        ParottaSetQuantity = new javax.swing.JSpinner();
        ChickenFriedRiceQuantity = new javax.swing.JSpinner();
        OothappamQuantity = new javax.swing.JSpinner();
        MuttonDosaQuantity = new javax.swing.JSpinner();
        SilonParottaQuantity = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderSum = new javax.swing.JTextArea();
        TotalPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TotalButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        PromoCode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mjn(evt);
            }
        });

        Idly.setText("IDLY -Rs 40");
        Idly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IdlyMouseClicked(evt);
            }
        });
        Idly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdlyActionPerformed(evt);
            }
        });

        Poori.setText("POORI-Rs 50");
        Poori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PooriActionPerformed(evt);
            }
        });

        Chappathi.setText("CHAPPATHI Rs 50");
        Chappathi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChappathiActionPerformed(evt);
            }
        });

        Dosa.setText("DOSA Rs 70");
        Dosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosaActionPerformed(evt);
            }
        });

        Pongal.setText("PONGAL -Rs 50");
        Pongal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PongalActionPerformed(evt);
            }
        });

        jLabel4.setText("DISHES");

        jLabel5.setText("QUANTITY");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Chappathi)
                    .addComponent(Poori)
                    .addComponent(Pongal)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Idly)
                        .addComponent(jLabel4))
                    .addComponent(Dosa))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PongalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChappathiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdlyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PooriQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(537, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Idly)
                    .addComponent(IdlyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Poori)
                    .addComponent(PooriQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chappathi)
                    .addComponent(ChappathiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dosa)
                    .addComponent(DosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pongal)
                    .addComponent(PongalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BREAKFAST", jPanel7);

        jLabel1.setText("DISHES");

        ChickenBiriyani.setText("CHICKEN BIRIYANI -Rs 130");
        ChickenBiriyani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenBiriyaniActionPerformed(evt);
            }
        });

        MuttonBiriyani.setText("MUTTON BIRIYANI Rs 170");
        MuttonBiriyani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuttonBiriyaniActionPerformed(evt);
            }
        });

        VegMeals.setText("VEG MEALS Rs 80");
        VegMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegMealsActionPerformed(evt);
            }
        });

        NonVegMeals.setText("NON VEG MEALS Rs 110");
        NonVegMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NonVegMealsActionPerformed(evt);
            }
        });

        GrilledChicken.setText("GRILLED CHICKEN Rs 360");
        GrilledChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrilledChickenActionPerformed(evt);
            }
        });

        jLabel2.setText("QUANTITY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(271, 271, 271)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChickenBiriyani)
                            .addComponent(NonVegMeals)
                            .addComponent(GrilledChicken)
                            .addComponent(VegMeals)
                            .addComponent(MuttonBiriyani))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MuttonBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChickenBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VegMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NonVegMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GrilledChickenQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChickenBiriyani)
                    .addComponent(ChickenBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MuttonBiriyani)
                    .addComponent(MuttonBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VegMeals)
                    .addComponent(VegMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NonVegMeals)
                    .addComponent(NonVegMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GrilledChicken)
                    .addComponent(GrilledChickenQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LUNCH", jPanel1);

        ParottaSet.setText("PAROTTA SET -Rs 45");
        ParottaSet.setToolTipText("");
        ParottaSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParottaSetActionPerformed(evt);
            }
        });

        jLabel6.setText("DISHES");

        ChickenFriedRice.setText("CHICKEN FRIED RICE-Rs 100");
        ChickenFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenFriedRiceActionPerformed(evt);
            }
        });

        Oothappam.setText("OOTHAPPAM-Rs 30");
        Oothappam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OothappamActionPerformed(evt);
            }
        });

        MuttonDosa.setText("MUTTON DOSA-Rs 150");
        MuttonDosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuttonDosaActionPerformed(evt);
            }
        });

        SilonParotta.setText("SILONPAROTTA -Rs 130");
        SilonParotta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilonParottaActionPerformed(evt);
            }
        });

        jLabel7.setText("QUANTITY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChickenFriedRice)
                            .addComponent(ParottaSet)
                            .addComponent(Oothappam)
                            .addComponent(MuttonDosa)
                            .addComponent(SilonParotta))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChickenFriedRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ParottaSetQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OothappamQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MuttonDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SilonParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ParottaSet)
                    .addComponent(ParottaSetQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChickenFriedRice)
                    .addComponent(ChickenFriedRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Oothappam)
                    .addComponent(OothappamQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MuttonDosa)
                    .addComponent(MuttonDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SilonParotta)
                    .addComponent(SilonParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DINNER", jPanel3);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel11.setText("DESERTS ARE NOT AVAILABLE IN THIS RESTAURANT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel11)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DESSERTS", jPanel4);

        OrderSum.setColumns(20);
        OrderSum.setRows(5);
        jScrollPane1.setViewportView(OrderSum);

        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });

        jLabel10.setText("DISHES ORDERED WITH THEIR PRICE");

        jButton1.setText("CASH ON DELIVERY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ONLINE PAYMENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TotalButton.setText("TOTAL");
        TotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("APPLY PROMOCODE");

        jButton3.setText("APPLY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(TotalPrice))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton3)
                                        .addGap(42, 42, 42)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                                .addGap(124, 124, 124))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(TotalButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ORDER SUMMARY", jPanel2);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("ANBAGAM MESS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel3)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PooriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PooriActionPerformed
        // TODO add your handling code here:
        
         double quantity = Double.parseDouble(PooriQuantity.getValue().toString());
         double pooriprice = 50;
        if(Poori.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Poori.getText()+"; ");
         double price = quantity*pooriprice;
         OrderSum.append("Quantity :"+PooriQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PooriActionPerformed

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         AddressInfo AI = new AddressInfo();
        AI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IdlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdlyMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_IdlyMouseClicked

    private void IdlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdlyActionPerformed
        // TODO add your handling code here:
       
         double quantity = Double.parseDouble(IdlyQuantity.getValue().toString());
         double Idlyprice = 40;
        if(Idly.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Idly.getText()+"; ");
         double price = quantity*Idlyprice;
         OrderSum.append("Quantity :"+IdlyQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_IdlyActionPerformed

    private void PongalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PongalActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(PongalQuantity.getValue().toString());
         double pongalprice = 50;
        if(Pongal.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Pongal.getText()+"; ");
         double price = quantity*pongalprice;
         OrderSum.append("Quantity :"+PongalQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PongalActionPerformed

    private void ChappathiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChappathiActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(ChappathiQuantity.getValue().toString());
         double Chappathiprice = 50;
        if(Chappathi.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Chappathi.getText()+"; ");
         double price = quantity*Chappathiprice;
         OrderSum.append("Quantity :"+ChappathiQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_ChappathiActionPerformed

    private void DosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(DosaQuantity.getValue().toString());
         double Dosaprice = 70;
         
        if(Dosa.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Dosa.getText()+"; ");
            OrderSum.append("Quantity :"+DosaQuantity.getValue()
         +" ;");
         double price = quantity*Dosaprice;
       
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_DosaActionPerformed

    private void TotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalButtonActionPerformed
        // TODO add your handling code here
       double total_price = 0;
       if(Idly.isSelected()){
        double quantity = Double.parseDouble(IdlyQuantity.getValue().toString());
        double Idlyprice = 40;
        double price = quantity*Idlyprice;
        total_price = total_price + price;
       }
       if(Poori.isSelected()){
        double quantity = Double.parseDouble(PooriQuantity.getValue().toString());
        double Pooriprice = 50;
        double price = quantity*Pooriprice;
        total_price = total_price + price;
       }
        if(Chappathi.isSelected()){
        double quantity = Double.parseDouble(ChappathiQuantity.getValue().toString());
        double Chappathiprice = 50;
        double price = quantity*Chappathiprice;
        total_price = total_price + price;
       }
         if(Dosa.isSelected()){
        double quantity = Double.parseDouble(DosaQuantity.getValue().toString());
        double Dosaprice = 70;
        double price = quantity*Dosaprice;
        total_price = total_price + price;
       }
          if(Pongal.isSelected()){
        double quantity = Double.parseDouble(PongalQuantity.getValue().toString());
        double Pongalprice = 50;
        double price = quantity*Pongalprice;
        total_price = total_price + price;
       }
          if(ChickenBiriyani.isSelected()){
        double quantity = Double.parseDouble(ChickenBiriyaniQuantity.getValue().toString());
        double ChickenBiriyaniprice = 130;
        double price = quantity*ChickenBiriyaniprice;
        total_price = total_price + price;
       }
          if(MuttonBiriyani.isSelected()){
        double quantity = Double.parseDouble(MuttonBiriyaniQuantity.getValue().toString());
        double MuttonBiriyaniprice = 170;
        double price = quantity*MuttonBiriyaniprice;
        total_price = total_price + price;
       }
         if(VegMeals.isSelected()){
        double quantity = Double.parseDouble(VegMealsQuantity.getValue().toString());
        double VegMealsprice = 80;
        double price = quantity*VegMealsprice;
        total_price = total_price + price;
       }
         if(NonVegMeals.isSelected()){
        double quantity = Double.parseDouble(NonVegMealsQuantity.getValue().toString());
        double NonVegMealsprice = 110;
        double price = quantity*NonVegMealsprice;
        total_price = total_price + price;
       }
          if(GrilledChicken.isSelected()){
        double quantity = Double.parseDouble(GrilledChickenQuantity.getValue().toString());
        double GrilledChickenprice = 360;
        double price = quantity*GrilledChickenprice;
        total_price = total_price + price;
       }
           if(ParottaSet.isSelected()){
        double quantity = Double.parseDouble(ParottaSetQuantity.getValue().toString());
        double ParottaSetprice = 45;
        double price = quantity*ParottaSetprice;
        total_price = total_price + price;
       }
            if(ChickenFriedRice.isSelected()){
        double quantity = Double.parseDouble(ChickenFriedRiceQuantity.getValue().toString());
        double ChickenFriedRiceprice = 100;
        double price = quantity*ChickenFriedRiceprice;
        total_price = total_price + price;
       }
             if(Oothappam.isSelected()){
        double quantity = Double.parseDouble(OothappamQuantity.getValue().toString());
        double Oothappamprice = 30;
        double price = quantity*Oothappamprice;
        total_price = total_price + price;
       }
              if(MuttonDosa.isSelected()){
        double quantity = Double.parseDouble(MuttonDosaQuantity.getValue().toString());
        double MuttonDosaprice = 150;
        double price = quantity*MuttonDosaprice;
        total_price = total_price + price;
       }
               if(SilonParotta.isSelected()){
        double quantity = Double.parseDouble(SilonParottaQuantity.getValue().toString());
        double SilonParottaprice = 130;
        double price = quantity*SilonParottaprice;
        total_price = total_price + price;
       }
         
       TotalPrice.setText(""+total_price);
          
    }//GEN-LAST:event_TotalButtonActionPerformed

    private void ChickenBiriyaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenBiriyaniActionPerformed
         double quantity = Double.parseDouble(ChickenBiriyaniQuantity.getValue().toString());
         double cb_price = 130;
        if(ChickenBiriyani.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+ChickenBiriyani.getText()+"; ");
         double price = quantity*cb_price;
         OrderSum.append("Quantity :"+ChickenBiriyaniQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
           
        }
    }//GEN-LAST:event_ChickenBiriyaniActionPerformed

    private void MuttonBiriyaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuttonBiriyaniActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(MuttonBiriyaniQuantity.getValue().toString());
         double mb_price = 170;
        if(MuttonBiriyani.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+MuttonBiriyani.getText()+"; ");
         double price = quantity*mb_price;
         OrderSum.append("Quantity :"+MuttonBiriyaniQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_MuttonBiriyaniActionPerformed

    private void VegMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegMealsActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(VegMealsQuantity.getValue().toString());
         double VegMealsprice = 80;
        if(VegMeals.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+VegMeals.getText()+"; ");
         double price = quantity*VegMealsprice;
         OrderSum.append("Quantity :"+VegMealsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_VegMealsActionPerformed

    private void NonVegMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NonVegMealsActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(NonVegMealsQuantity.getValue().toString());
         double NonVegMealsprice = 110;
        if(NonVegMeals.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+NonVegMeals.getText()+"; ");
         double price = quantity*NonVegMealsprice;
         OrderSum.append("Quantity :"+NonVegMealsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_NonVegMealsActionPerformed

    private void GrilledChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrilledChickenActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(GrilledChickenQuantity.getValue().toString());
         double GrilledChickenprice = 360;
        if(GrilledChicken.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+GrilledChicken.getText()+"; ");
         double price = quantity*GrilledChickenprice;
         OrderSum.append("Quantity :"+GrilledChickenQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_GrilledChickenActionPerformed

    private void ParottaSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParottaSetActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(ParottaSetQuantity.getValue().toString());
         double ParottaSetprice = 45;
        if(ParottaSet.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+ParottaSet.getText()+"; ");
         double price = quantity*ParottaSetprice;
         OrderSum.append("Quantity :"+ParottaSetQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_ParottaSetActionPerformed

    private void ChickenFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenFriedRiceActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(ChickenFriedRiceQuantity.getValue().toString());
         double ChickenFriedRiceprice = 100;
        if(ChickenFriedRice.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+ChickenFriedRice.getText()+"; ");
         double price = quantity*ChickenFriedRiceprice;
         OrderSum.append("Quantity :"+ChickenFriedRiceQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_ChickenFriedRiceActionPerformed

    private void OothappamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OothappamActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(OothappamQuantity.getValue().toString());
         double Oothappamprice = 30;
        if(Oothappam.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Oothappam.getText()+"; ");
         double price = quantity*Oothappamprice;
         OrderSum.append("Quantity :"+OothappamQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_OothappamActionPerformed

    private void MuttonDosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuttonDosaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(MuttonDosaQuantity.getValue().toString());
         double MuttonDosaprice = 150;
        if(MuttonDosa.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+MuttonDosa.getText()+"; ");
         double price = quantity*MuttonDosaprice;
         OrderSum.append("Quantity :"+MuttonDosaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_MuttonDosaActionPerformed

    private void SilonParottaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilonParottaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(SilonParottaQuantity.getValue().toString());
         double SilonParottaprice = 130;
        if(SilonParotta.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+SilonParotta.getText()+"; ");
         double price = quantity*SilonParottaprice;
         OrderSum.append("Quantity :"+SilonParottaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_SilonParottaActionPerformed

    private void mjn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mjn
        // TODO add your handling code here:
    }//GEN-LAST:event_mjn

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame();
        double Total = Double.parseDouble(TotalPrice.getText());
        if(PromoCode.getText().equals("DIWALI20")){
           double Disc_Amount = Total-(Total*0.3);
           TotalPrice.setText(""+Disc_Amount);
        }
        else{
        JOptionPane.showMessageDialog(f,"Enter a valid code");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         OnlinePayment OP = new OnlinePayment();
        OP.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anbagam_Mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anbagam_Mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anbagam_Mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anbagam_Mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anbagam_Mess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Chappathi;
    private javax.swing.JSpinner ChappathiQuantity;
    private javax.swing.JCheckBox ChickenBiriyani;
    private javax.swing.JSpinner ChickenBiriyaniQuantity;
    private javax.swing.JCheckBox ChickenFriedRice;
    private javax.swing.JSpinner ChickenFriedRiceQuantity;
    private javax.swing.JCheckBox Dosa;
    private javax.swing.JSpinner DosaQuantity;
    private javax.swing.JCheckBox GrilledChicken;
    private javax.swing.JSpinner GrilledChickenQuantity;
    private javax.swing.JCheckBox Idly;
    private javax.swing.JSpinner IdlyQuantity;
    private javax.swing.JCheckBox MuttonBiriyani;
    private javax.swing.JSpinner MuttonBiriyaniQuantity;
    private javax.swing.JCheckBox MuttonDosa;
    private javax.swing.JSpinner MuttonDosaQuantity;
    private javax.swing.JCheckBox NonVegMeals;
    private javax.swing.JSpinner NonVegMealsQuantity;
    private javax.swing.JCheckBox Oothappam;
    private javax.swing.JSpinner OothappamQuantity;
    private javax.swing.JTextArea OrderSum;
    private javax.swing.JCheckBox ParottaSet;
    private javax.swing.JSpinner ParottaSetQuantity;
    private javax.swing.JCheckBox Pongal;
    private javax.swing.JSpinner PongalQuantity;
    private javax.swing.JCheckBox Poori;
    private javax.swing.JSpinner PooriQuantity;
    private javax.swing.JTextField PromoCode;
    private javax.swing.JCheckBox SilonParotta;
    private javax.swing.JSpinner SilonParottaQuantity;
    private javax.swing.JButton TotalButton;
    private javax.swing.JTextField TotalPrice;
    private javax.swing.JCheckBox VegMeals;
    private javax.swing.JSpinner VegMealsQuantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private String String(int price) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
