/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddelivery;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vasanth
 */
public class Mariott extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant_Anjappar
     */
    public Mariott() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        Casserole = new javax.swing.JCheckBox();
        Cereals = new javax.swing.JCheckBox();
        Bagel = new javax.swing.JCheckBox();
        ButterNaan = new javax.swing.JCheckBox();
        OatMeals = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CasseroleQuantity = new javax.swing.JSpinner();
        CerealQuantity = new javax.swing.JSpinner();
        BagelQuantity = new javax.swing.JSpinner();
        ButterNaanQuantity = new javax.swing.JSpinner();
        OatMealsQuantity = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SmokedBBQ = new javax.swing.JCheckBox();
        MasalaPrawn = new javax.swing.JCheckBox();
        PorkRibs = new javax.swing.JCheckBox();
        MuttonKorma = new javax.swing.JCheckBox();
        LambChops = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        SmokedBBQQuantity = new javax.swing.JSpinner();
        MasalaPrawnQuantity = new javax.swing.JSpinner();
        PorkRibsQuantity = new javax.swing.JSpinner();
        MuttonKormaQuantity = new javax.swing.JSpinner();
        LambChopsQuantity = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        ChickenNoodles = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        SchezwanNoodles = new javax.swing.JCheckBox();
        TandooriRoti = new javax.swing.JCheckBox();
        RumaliRoti = new javax.swing.JCheckBox();
        ChilliParotta = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        ChickenNoodlesQuantity = new javax.swing.JSpinner();
        SchezwanNoodlesQuantity = new javax.swing.JSpinner();
        TandooriRotiQuantity = new javax.swing.JSpinner();
        RumaliRotiQuantity = new javax.swing.JSpinner();
        ChilliParottaQuantity = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        Falooda = new javax.swing.JCheckBox();
        FigShake = new javax.swing.JCheckBox();
        LimeJuice = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FaloodaQuantity = new javax.swing.JSpinner();
        FigShakeQuantity = new javax.swing.JSpinner();
        LimeJuiceQuantity = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderSum = new javax.swing.JTextArea();
        TotalPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TotalButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        PromoCode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mjn(evt);
            }
        });

        Casserole.setText("CASSEROLE-Rs 150");
        Casserole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CasseroleMouseClicked(evt);
            }
        });
        Casserole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasseroleActionPerformed(evt);
            }
        });

        Cereals.setText("CEREAL-Rs 50");
        Cereals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerealsActionPerformed(evt);
            }
        });

        Bagel.setText("BAGEL Rs 80");
        Bagel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagelActionPerformed(evt);
            }
        });

        ButterNaan.setText("BUTTER NAAN Rs 90");
        ButterNaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButterNaanActionPerformed(evt);
            }
        });

        OatMeals.setText("OAT MEAL -Rs 70");
        OatMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OatMealsActionPerformed(evt);
            }
        });

        jLabel4.setText("DISHES");

        jLabel5.setText("QUANTITY");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ButterNaan)
                        .addComponent(Bagel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Cereals, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(OatMeals, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Casserole)
                        .addComponent(jLabel4)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OatMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BagelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButterNaanQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CasseroleQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CerealQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(521, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Casserole)
                    .addComponent(CasseroleQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cereals)
                    .addComponent(CerealQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bagel)
                    .addComponent(BagelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButterNaan)
                    .addComponent(ButterNaanQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OatMeals)
                    .addComponent(OatMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BREAKFAST", jPanel7);

        jLabel1.setText("DISHES");

        SmokedBBQ.setText("SMOKED BBQ -Rs 300");
        SmokedBBQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmokedBBQActionPerformed(evt);
            }
        });

        MasalaPrawn.setText("MASALA PRAWN Rs 280");
        MasalaPrawn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasalaPrawnActionPerformed(evt);
            }
        });

        PorkRibs.setText("PORK RIBS Rs 150");
        PorkRibs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorkRibsActionPerformed(evt);
            }
        });

        MuttonKorma.setText("MUTTON KORMA Rs 300");
        MuttonKorma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuttonKormaActionPerformed(evt);
            }
        });

        LambChops.setText("LAMB CHOPS Rs 60");
        LambChops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LambChopsActionPerformed(evt);
            }
        });

        jLabel2.setText("QUANTITY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(271, 271, 271)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SmokedBBQ)
                            .addComponent(MuttonKorma)
                            .addComponent(LambChops)
                            .addComponent(PorkRibs)
                            .addComponent(MasalaPrawn))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MasalaPrawnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SmokedBBQQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PorkRibsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MuttonKormaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LambChopsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SmokedBBQ)
                    .addComponent(SmokedBBQQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MasalaPrawn)
                    .addComponent(MasalaPrawnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PorkRibs)
                    .addComponent(PorkRibsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MuttonKorma)
                    .addComponent(MuttonKormaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LambChops)
                    .addComponent(LambChopsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LUNCH", jPanel1);

        ChickenNoodles.setText("CHICKEN NOODLES -Rs 90");
        ChickenNoodles.setToolTipText("");
        ChickenNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenNoodlesActionPerformed(evt);
            }
        });

        jLabel6.setText("DISHES");

        SchezwanNoodles.setText("SCHEZWAN NOODLES -Rs 100");
        SchezwanNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchezwanNoodlesActionPerformed(evt);
            }
        });

        TandooriRoti.setText("TANDOORI ROTI -Rs 70");
        TandooriRoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TandooriRotiActionPerformed(evt);
            }
        });

        RumaliRoti.setText("RUMALI ROTI -Rs 90");
        RumaliRoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RumaliRotiActionPerformed(evt);
            }
        });

        ChilliParotta.setText("CHILLI PAROTTA -Rs 80");
        ChilliParotta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChilliParottaActionPerformed(evt);
            }
        });

        jLabel7.setText("QUANTITY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SchezwanNoodles)
                            .addComponent(ChickenNoodles)
                            .addComponent(TandooriRoti)
                            .addComponent(RumaliRoti)
                            .addComponent(ChilliParotta))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SchezwanNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChickenNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TandooriRotiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RumaliRotiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChilliParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChickenNoodles)
                    .addComponent(ChickenNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SchezwanNoodles)
                    .addComponent(SchezwanNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TandooriRoti)
                    .addComponent(TandooriRotiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RumaliRoti)
                    .addComponent(RumaliRotiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChilliParotta)
                    .addComponent(ChilliParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DINNER", jPanel3);

        Falooda.setText("FALOODA -Rs 170");
        Falooda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaloodaActionPerformed(evt);
            }
        });

        FigShake.setText("FIG SHAKE -Rs 150");
        FigShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FigShakeActionPerformed(evt);
            }
        });

        LimeJuice.setText("LIME JUICE -Rs 50");
        LimeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimeJuiceActionPerformed(evt);
            }
        });

        jLabel8.setText("DISHES");

        jLabel9.setText("QUANTITY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Falooda)
                            .addComponent(FigShake)
                            .addComponent(LimeJuice))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FigShakeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FaloodaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LimeJuiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(481, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Falooda)
                    .addComponent(FaloodaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FigShake)
                    .addComponent(FigShakeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimeJuice)
                    .addComponent(LimeJuiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DESSERTS", jPanel4);

        OrderSum.setColumns(20);
        OrderSum.setRows(5);
        jScrollPane1.setViewportView(OrderSum);

        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });

        jLabel10.setText("DISHES ORDERED WITH THEIR PRICE");

        jButton1.setText("CASH ON DELIVERY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ONLINE PAYMENT");

        TotalButton.setText("TOTAL");
        TotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("APPLY PROMOCODE");

        jButton3.setText("APPLY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(TotalPrice))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                                .addGap(124, 124, 124))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(TotalButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ORDER SUMMARY", jPanel2);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("MARIOTT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel3)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerealsActionPerformed
        // TODO add your handling code here:
        
         double quantity = Double.parseDouble(CerealQuantity.getValue().toString());
         double pooriprice = 50;
        if(Cereals.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Cereals.getText()+"; ");
         double price = quantity*pooriprice;
         OrderSum.append("Quantity :"+CerealQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_CerealsActionPerformed

    private void FaloodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaloodaActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(FaloodaQuantity.getValue().toString());
         double Faloodaprice = 170;
        if(Falooda.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Falooda.getText()+"; ");
         double price = quantity*Faloodaprice;
         OrderSum.append("Quantity :"+FaloodaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_FaloodaActionPerformed

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AddressInfo AI = new AddressInfo();
        AI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CasseroleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CasseroleMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_CasseroleMouseClicked

    private void CasseroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasseroleActionPerformed
        // TODO add your handling code here:
       
         double quantity = Double.parseDouble(CasseroleQuantity.getValue().toString());
         double Casseroleprice = 150;
        if(Casserole.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Casserole.getText()+"; ");
         double price = quantity*Casseroleprice;
         OrderSum.append("Quantity :"+CasseroleQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_CasseroleActionPerformed

    private void OatMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OatMealsActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(OatMealsQuantity.getValue().toString());
         double OatMealsprice = 70;
        if(OatMeals.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+OatMeals.getText()+"; ");
         double price = quantity*OatMealsprice;
         OrderSum.append("Quantity :"+OatMealsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_OatMealsActionPerformed

    private void BagelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagelActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(BagelQuantity.getValue().toString());
         double Bagelprice = 80;
        if(Bagel.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Bagel.getText()+"; ");
         double price = quantity*Bagelprice;
         OrderSum.append("Quantity :"+BagelQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_BagelActionPerformed

    private void ButterNaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButterNaanActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(ButterNaanQuantity.getValue().toString());
         double ButterNaanprice = 90;
          OrderSum.append("\n"+ButterNaan.getText()+"; ");
            OrderSum.append("Quantity :"+ButterNaanQuantity.getValue()
         +" ;");
        if(ButterNaan.isSelected()){
           // double price = quantity*dosaprice;
        
         double price = quantity*ButterNaanprice;
       
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_ButterNaanActionPerformed

    private void TotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalButtonActionPerformed
        // TODO add your handling code here
       double total_price = 0;
       if(Falooda.isSelected()){
            double quantity = Double.parseDouble(FaloodaQuantity.getValue().toString());
            double Faloodaprice = 170;
            double price = quantity*Faloodaprice;
            total_price = total_price + price;
         }
        if(LimeJuice.isSelected()){
            double quantity = Double.parseDouble(LimeJuiceQuantity.getValue().toString());
            double LimeJuiceprice = 50;
            double price = quantity*LimeJuiceprice;
            total_price = total_price + price;
         }
         if(FigShake.isSelected()){
            double quantity = Double.parseDouble(FigShakeQuantity.getValue().toString());
            double LimeJuiceprice = 150;
            double price = quantity*LimeJuiceprice;
            total_price = total_price + price;
         }
       if(Casserole.isSelected()){
        double quantity = Double.parseDouble(CasseroleQuantity.getValue().toString());
        double Casseroleprice = 150;
        double price = quantity*Casseroleprice;
        total_price = total_price + price;
       }
       if(Cereals.isSelected()){
        double quantity = Double.parseDouble(CerealQuantity.getValue().toString());
        double Cerealsprice = 50;
        double price = quantity*Cerealsprice;
        total_price = total_price + price;
       }
        if(Bagel.isSelected()){
        double quantity = Double.parseDouble(BagelQuantity.getValue().toString());
        double Bagerprice = 80;
        double price = quantity*Bagerprice;
        total_price = total_price + price;
       }
         if(ButterNaan.isSelected()){
        double quantity = Double.parseDouble(ButterNaanQuantity.getValue().toString());
        double ButterNaanprice = 90;
        double price = quantity*ButterNaanprice;
        total_price = total_price + price;
       }
          if(OatMeals.isSelected()){
        double quantity = Double.parseDouble(OatMealsQuantity.getValue().toString());
        double OatMealsprice = 70;
        double price = quantity*OatMealsprice;
        total_price = total_price + price;
       }
          if(SmokedBBQ.isSelected()){
        double quantity = Double.parseDouble(SmokedBBQQuantity.getValue().toString());
        double SmokedBBQprice = 150*2;
        double price = quantity*SmokedBBQprice;
        total_price = total_price + price;
       }
          if(MasalaPrawn.isSelected()){
        double quantity = Double.parseDouble(MasalaPrawnQuantity.getValue().toString());
        double MasalaPrawnprice = 280;
        double price = quantity*MasalaPrawnprice;
        total_price = total_price + price;
       }
         if(PorkRibs.isSelected()){
        double quantity = Double.parseDouble(PorkRibsQuantity.getValue().toString());
        double PorkRibsprice = 150;
        double price = quantity*PorkRibsprice;
        total_price = total_price + price;
       }
         if(MuttonKorma.isSelected()){
        double quantity = Double.parseDouble(MuttonKormaQuantity.getValue().toString());
        double MuttonKormaprice = 300;
        double price = quantity*MuttonKormaprice;
        total_price = total_price + price;
       }
          if(LambChops.isSelected()){
        double quantity = Double.parseDouble(LambChopsQuantity.getValue().toString());
        double LambChopsprice = 60;
        double price = quantity*LambChopsprice;
        total_price = total_price + price;
       }
           if(ChickenNoodles.isSelected()){
        double quantity = Double.parseDouble(ChickenNoodlesQuantity.getValue().toString());
        double ChickenNoodlesprice = 90;
        double price = quantity*ChickenNoodlesprice;
        total_price = total_price + price;
       }
            if(SchezwanNoodles.isSelected()){
        double quantity = Double.parseDouble(SchezwanNoodlesQuantity.getValue().toString());
        double SchezwanNoodlesprice = 100;
        double price = quantity*SchezwanNoodlesprice;
        total_price = total_price + price;
       }
             if(TandooriRoti.isSelected()){
        double quantity = Double.parseDouble(TandooriRotiQuantity.getValue().toString());
        double TandooriRotiprice = 70;
        double price = quantity*TandooriRotiprice;
        total_price = total_price + price;
       }
              if(RumaliRoti.isSelected()){
        double quantity = Double.parseDouble(RumaliRotiQuantity.getValue().toString());
        double RumaliRotiprice = 90;
        double price = quantity*RumaliRotiprice;
        total_price = total_price + price;
       }
               if(ChilliParotta.isSelected()){
        double quantity = Double.parseDouble(ChilliParottaQuantity.getValue().toString());
        double ChilliParottaprice = 130;
        double price = quantity*ChilliParottaprice;
        total_price = total_price + price;
       }
         
       TotalPrice.setText(""+total_price);
          
    }//GEN-LAST:event_TotalButtonActionPerformed

    private void SmokedBBQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmokedBBQActionPerformed
         double quantity = Double.parseDouble(SmokedBBQQuantity.getValue().toString());
         double SmokedBBQprice = 300;
        if(SmokedBBQ.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+SmokedBBQ.getText()+"; ");
         double price = quantity*SmokedBBQprice;
         OrderSum.append("Quantity :"+SmokedBBQQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
           
        }
    }//GEN-LAST:event_SmokedBBQActionPerformed

    private void MasalaPrawnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasalaPrawnActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(MasalaPrawnQuantity.getValue().toString());
         double MasalaPrawnprice = 280;
        if(MasalaPrawn.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+MasalaPrawn.getText()+"; ");
         double price = quantity*MasalaPrawnprice;
         OrderSum.append("Quantity :"+MasalaPrawnQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_MasalaPrawnActionPerformed

    private void MuttonKormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuttonKormaActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(MuttonKormaQuantity.getValue().toString());
         double MuttonKormaprice = 300;
        if(MuttonKorma.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+MuttonKorma.getText()+"; ");
         double price = quantity*MuttonKormaprice;
         OrderSum.append("Quantity :"+MuttonKormaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_MuttonKormaActionPerformed

    private void LambChopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LambChopsActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(LambChopsQuantity.getValue().toString());
         double LambChopsprice = 60;
        if(LambChops.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+LambChops.getText()+"; ");
         double price = quantity*LambChopsprice;
         OrderSum.append("Quantity :"+LambChopsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_LambChopsActionPerformed

    private void ChickenNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenNoodlesActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(ChickenNoodlesQuantity.getValue().toString());
         double c_noodlesprice = 90;
        if(ChickenNoodles.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+ChickenNoodles.getText()+"; ");
         double price = quantity*c_noodlesprice;
         OrderSum.append("Quantity :"+ChickenNoodlesQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_ChickenNoodlesActionPerformed

    private void SchezwanNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchezwanNoodlesActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(SchezwanNoodlesQuantity.getValue().toString());
         double s_noodlesprice = 100;
        if(SchezwanNoodles.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+SchezwanNoodles.getText()+"; ");
         double price = quantity*s_noodlesprice;
         OrderSum.append("Quantity :"+SchezwanNoodlesQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_SchezwanNoodlesActionPerformed

    private void TandooriRotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TandooriRotiActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(TandooriRotiQuantity.getValue().toString());
         double t_rotiprice = 70;
        if(TandooriRoti.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+TandooriRoti.getText()+"; ");
         double price = quantity*t_rotiprice;
         OrderSum.append("Quantity :"+TandooriRotiQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_TandooriRotiActionPerformed

    private void RumaliRotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RumaliRotiActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(RumaliRotiQuantity.getValue().toString());
         double r_rotiprice = 90;
        if(RumaliRoti.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+RumaliRoti.getText()+"; ");
         double price = quantity*r_rotiprice;
         OrderSum.append("Quantity :"+RumaliRotiQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_RumaliRotiActionPerformed

    private void ChilliParottaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChilliParottaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(ChilliParottaQuantity.getValue().toString());
         double ChilliParottaprice = 130;
        if(ChilliParotta.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+ChilliParotta.getText()+"; ");
         double price = quantity*ChilliParottaprice;
         OrderSum.append("Quantity :"+ChilliParottaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_ChilliParottaActionPerformed

    private void mjn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mjn
        // TODO add your handling code here:
    }//GEN-LAST:event_mjn

    private void PorkRibsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorkRibsActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(PorkRibsQuantity.getValue().toString());
        double PorkRibsprice = 150;
        if(PorkRibs.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+PorkRibs.getText()+"; ");
            double price = quantity*PorkRibsprice;
            OrderSum.append("Quantity :"+PorkRibsQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_PorkRibsActionPerformed

    private void FigShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FigShakeActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(FigShakeQuantity.getValue().toString());
        double FigShakeprice = 150;
        if(FigShake.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+FigShake.getText()+"; ");
            double price = quantity*FigShakeprice;
            OrderSum.append("Quantity :"+FigShakeQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_FigShakeActionPerformed

    private void LimeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimeJuiceActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(LimeJuiceQuantity.getValue().toString());
        double LimeJuiceprice = 50;
        if(LimeJuice.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+LimeJuice.getText()+"; ");
            double price = quantity*LimeJuiceprice;
            OrderSum.append("Quantity :"+LimeJuiceQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_LimeJuiceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame();
        double Total = Double.parseDouble(TotalPrice.getText());
        if(PromoCode.getText().equals("DIWALI20")){
           double Disc_Amount = Total-(Total*0.3);
           TotalPrice.setText(""+Disc_Amount);
        }
        else{
        JOptionPane.showMessageDialog(f,"Enter a valid code");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mariott.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mariott.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mariott.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mariott.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mariott().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Bagel;
    private javax.swing.JSpinner BagelQuantity;
    private javax.swing.JCheckBox ButterNaan;
    private javax.swing.JSpinner ButterNaanQuantity;
    private javax.swing.JCheckBox Casserole;
    private javax.swing.JSpinner CasseroleQuantity;
    private javax.swing.JSpinner CerealQuantity;
    private javax.swing.JCheckBox Cereals;
    private javax.swing.JCheckBox ChickenNoodles;
    private javax.swing.JSpinner ChickenNoodlesQuantity;
    private javax.swing.JCheckBox ChilliParotta;
    private javax.swing.JSpinner ChilliParottaQuantity;
    private javax.swing.JCheckBox Falooda;
    private javax.swing.JSpinner FaloodaQuantity;
    private javax.swing.JCheckBox FigShake;
    private javax.swing.JSpinner FigShakeQuantity;
    private javax.swing.JCheckBox LambChops;
    private javax.swing.JSpinner LambChopsQuantity;
    private javax.swing.JCheckBox LimeJuice;
    private javax.swing.JSpinner LimeJuiceQuantity;
    private javax.swing.JCheckBox MasalaPrawn;
    private javax.swing.JSpinner MasalaPrawnQuantity;
    private javax.swing.JCheckBox MuttonKorma;
    private javax.swing.JSpinner MuttonKormaQuantity;
    private javax.swing.JCheckBox OatMeals;
    private javax.swing.JSpinner OatMealsQuantity;
    private javax.swing.JTextArea OrderSum;
    private javax.swing.JCheckBox PorkRibs;
    private javax.swing.JSpinner PorkRibsQuantity;
    private javax.swing.JTextField PromoCode;
    private javax.swing.JCheckBox RumaliRoti;
    private javax.swing.JSpinner RumaliRotiQuantity;
    private javax.swing.JCheckBox SchezwanNoodles;
    private javax.swing.JSpinner SchezwanNoodlesQuantity;
    private javax.swing.JCheckBox SmokedBBQ;
    private javax.swing.JSpinner SmokedBBQQuantity;
    private javax.swing.JCheckBox TandooriRoti;
    private javax.swing.JSpinner TandooriRotiQuantity;
    private javax.swing.JButton TotalButton;
    private javax.swing.JTextField TotalPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private String String(int price) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
