/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddelivery;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vasanth
 */
public class Restaurant_a2b extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant_Anjappar
     */
    public Restaurant_a2b() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        MasalDosa = new javax.swing.JCheckBox();
        Adai = new javax.swing.JCheckBox();
        SambarIdly = new javax.swing.JCheckBox();
        PodiDosa = new javax.swing.JCheckBox();
        Pongal = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MasalDosaQuantity = new javax.swing.JSpinner();
        AdaiQuantity = new javax.swing.JSpinner();
        SambarIdlyQuantity = new javax.swing.JSpinner();
        PodiDosaQuantity = new javax.swing.JSpinner();
        PongalQuantity = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Puliyodharai = new javax.swing.JCheckBox();
        MealMakerBiriyani = new javax.swing.JCheckBox();
        ComboMeals = new javax.swing.JCheckBox();
        FullMeals = new javax.swing.JCheckBox();
        BabyMeals = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        PuliyodharaiQuantity = new javax.swing.JSpinner();
        MealMakerBiriyaniQuantity = new javax.swing.JSpinner();
        ComboMealsQuantity = new javax.swing.JSpinner();
        FullMealsQuantity = new javax.swing.JSpinner();
        BabyMealsQuantity = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        AlooParotta = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        SchezwanNoodles = new javax.swing.JCheckBox();
        VegNuggets = new javax.swing.JCheckBox();
        RumaliRoti = new javax.swing.JCheckBox();
        Pasta = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        AlooParottaQuantity = new javax.swing.JSpinner();
        SchezwanNoodlesQuantity = new javax.swing.JSpinner();
        VegNuggetsQuantity = new javax.swing.JSpinner();
        RumaliRotiQuantity = new javax.swing.JSpinner();
        PastaQuantity = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        Falooda = new javax.swing.JCheckBox();
        FigShake = new javax.swing.JCheckBox();
        LimeJuice = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FaloodaQuantity = new javax.swing.JSpinner();
        FigShakeQuantity = new javax.swing.JSpinner();
        LimeJuiceQuantity = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderSum = new javax.swing.JTextArea();
        TotalPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TotalButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        PromoCode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mjn(evt);
            }
        });

        MasalDosa.setText("MASAL DOSA -Rs 120");
        MasalDosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MasalDosaMouseClicked(evt);
            }
        });
        MasalDosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasalDosaActionPerformed(evt);
            }
        });

        Adai.setText("ADAI-Rs 60");
        Adai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdaiActionPerformed(evt);
            }
        });

        SambarIdly.setText("SAMBAR IDLY Rs 60");
        SambarIdly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SambarIdlyActionPerformed(evt);
            }
        });

        PodiDosa.setText("PODI DOSA Rs 80");
        PodiDosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PodiDosaActionPerformed(evt);
            }
        });

        Pongal.setText("PONGAL -Rs 70");
        Pongal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PongalActionPerformed(evt);
            }
        });

        jLabel4.setText("DISHES");

        jLabel5.setText("QUANTITY");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SambarIdly)
                    .addComponent(Adai)
                    .addComponent(Pongal)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(MasalDosa)
                        .addComponent(jLabel4))
                    .addComponent(PodiDosa))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PongalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SambarIdlyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PodiDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MasalDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdaiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(515, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MasalDosa)
                    .addComponent(MasalDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adai)
                    .addComponent(AdaiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SambarIdly)
                    .addComponent(SambarIdlyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PodiDosa)
                    .addComponent(PodiDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pongal)
                    .addComponent(PongalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BREAKFAST", jPanel7);

        jLabel1.setText("DISHES");

        Puliyodharai.setText("PULIYODHARAI -Rs 50");
        Puliyodharai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuliyodharaiActionPerformed(evt);
            }
        });

        MealMakerBiriyani.setText("MEAL MAKER BIRIYANI Rs 70");
        MealMakerBiriyani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealMakerBiriyaniActionPerformed(evt);
            }
        });

        ComboMeals.setText("COMBO MEALS Rs 150");
        ComboMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMealsActionPerformed(evt);
            }
        });

        FullMeals.setText("FULL MEALS Rs 100");
        FullMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullMealsActionPerformed(evt);
            }
        });

        BabyMeals.setText("BABY MEALS Rs 60");
        BabyMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BabyMealsActionPerformed(evt);
            }
        });

        jLabel2.setText("QUANTITY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(271, 271, 271)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Puliyodharai)
                            .addComponent(FullMeals)
                            .addComponent(BabyMeals)
                            .addComponent(ComboMeals)
                            .addComponent(MealMakerBiriyani))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MealMakerBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PuliyodharaiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FullMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BabyMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Puliyodharai)
                    .addComponent(PuliyodharaiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MealMakerBiriyani)
                    .addComponent(MealMakerBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboMeals)
                    .addComponent(ComboMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FullMeals)
                    .addComponent(FullMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BabyMeals)
                    .addComponent(BabyMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LUNCH", jPanel1);

        AlooParotta.setText("ALOOPAROTTA -Rs 90");
        AlooParotta.setToolTipText("");
        AlooParotta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlooParottaActionPerformed(evt);
            }
        });

        jLabel6.setText("DISHES");

        SchezwanNoodles.setText("SCHEZWAN NOODLES -Rs 100");
        SchezwanNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchezwanNoodlesActionPerformed(evt);
            }
        });

        VegNuggets.setText("VEG NUGGETS -Rs 70");
        VegNuggets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegNuggetsActionPerformed(evt);
            }
        });

        RumaliRoti.setText("RUMALI ROTI -Rs 90");
        RumaliRoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RumaliRotiActionPerformed(evt);
            }
        });

        Pasta.setText("PASTA-Rs 70");
        Pasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastaActionPerformed(evt);
            }
        });

        jLabel7.setText("QUANTITY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SchezwanNoodles)
                            .addComponent(AlooParotta)
                            .addComponent(VegNuggets)
                            .addComponent(RumaliRoti)
                            .addComponent(Pasta))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SchezwanNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlooParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VegNuggetsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RumaliRotiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PastaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlooParotta)
                    .addComponent(AlooParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SchezwanNoodles)
                    .addComponent(SchezwanNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VegNuggets)
                    .addComponent(VegNuggetsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RumaliRoti)
                    .addComponent(RumaliRotiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pasta)
                    .addComponent(PastaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DINNER", jPanel3);

        Falooda.setText("FALOODA -Rs 170");
        Falooda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaloodaActionPerformed(evt);
            }
        });

        FigShake.setText("FIG SHAKE -Rs 150");
        FigShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FigShakeActionPerformed(evt);
            }
        });

        LimeJuice.setText("LIME JUICE -Rs 50");
        LimeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimeJuiceActionPerformed(evt);
            }
        });

        jLabel8.setText("DISHES");

        jLabel9.setText("QUANTITY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Falooda)
                            .addComponent(FigShake)
                            .addComponent(LimeJuice))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FigShakeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FaloodaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LimeJuiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(481, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Falooda)
                    .addComponent(FaloodaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FigShake)
                    .addComponent(FigShakeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimeJuice)
                    .addComponent(LimeJuiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DESSERTS", jPanel4);

        OrderSum.setColumns(20);
        OrderSum.setRows(5);
        jScrollPane1.setViewportView(OrderSum);

        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });

        jLabel10.setText("DISHES ORDERED WITH THEIR PRICE");

        jButton1.setText("CASH ON DELIVERY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ONLINE PAYMENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TotalButton.setText("TOTAL");
        TotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("APPLY PROMOCODE");

        jButton3.setText("APPLY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel11)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(TotalPrice))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                                .addGap(124, 124, 124))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(TotalButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ORDER SUMMARY", jPanel2);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("a2b RESTAURANT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdaiActionPerformed
        // TODO add your handling code here:
        
         double quantity = Double.parseDouble(AdaiQuantity.getValue().toString());
         double Adaiprice = 60;
        if(Adai.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Adai.getText()+"; ");
         double price = quantity*Adaiprice;
         OrderSum.append("Quantity :"+AdaiQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_AdaiActionPerformed

    private void FaloodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaloodaActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(FaloodaQuantity.getValue().toString());
         double Faloodaprice = 170;
        if(Falooda.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Falooda.getText()+"; ");
         double price = quantity*Faloodaprice;
         OrderSum.append("Quantity :"+FaloodaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_FaloodaActionPerformed

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         AddressInfo AI = new AddressInfo();
        AI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MasalDosaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasalDosaMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_MasalDosaMouseClicked

    private void MasalDosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasalDosaActionPerformed
        // TODO add your handling code here:
       
         double quantity = Double.parseDouble(MasalDosaQuantity.getValue().toString());
         double MasalDosaprice = 120;
        if(MasalDosa.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+MasalDosa.getText()+"; ");
         double price = quantity*MasalDosaprice;
         OrderSum.append("Quantity :"+MasalDosaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_MasalDosaActionPerformed

    private void PongalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PongalActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(PongalQuantity.getValue().toString());
         double pongalprice = 70;
        if(Pongal.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Pongal.getText()+"; ");
         double price = quantity*pongalprice;
         OrderSum.append("Quantity :"+PongalQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PongalActionPerformed

    private void SambarIdlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SambarIdlyActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(SambarIdlyQuantity.getValue().toString());
         double SambarIdlyprice = 60;
        if(SambarIdly.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+SambarIdly.getText()+"; ");
         double price = quantity*SambarIdlyprice;
         OrderSum.append("Quantity :"+SambarIdlyQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_SambarIdlyActionPerformed

    private void PodiDosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PodiDosaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(PodiDosaQuantity.getValue().toString());
         double PodiDosaprice = 80;
          OrderSum.append("\n"+PodiDosa.getText()+"; ");
            OrderSum.append("Quantity :"+PodiDosaQuantity.getValue()
         +" ;");
        if(PodiDosa.isSelected()){
           // double price = quantity*dosaprice;
        
         double price = quantity*PodiDosaprice;
       
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PodiDosaActionPerformed

    private void TotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalButtonActionPerformed
        // TODO add your handling code here
       double total_price = 0;
        if(LimeJuice.isSelected()){
            double quantity = Double.parseDouble(LimeJuiceQuantity.getValue().toString());
            double LimeJuiceprice = 50;
            double price = quantity*LimeJuiceprice;
            total_price = total_price + price;
         }
         if(Falooda.isSelected()){
            double quantity = Double.parseDouble(FaloodaQuantity.getValue().toString());
            double Faloodaprice = 170;
            double price = quantity*Faloodaprice;
            total_price = total_price + price;
         }
         if(FigShake.isSelected()){
            double quantity = Double.parseDouble(FigShakeQuantity.getValue().toString());
            double FigShake = 150;
            double price = quantity*FigShake;
            total_price = total_price + price;
         }
       if(MasalDosa.isSelected()){
        double quantity = Double.parseDouble(MasalDosaQuantity.getValue().toString());
        double MasalDosaprice = 120;
        double price = quantity*MasalDosaprice;
        total_price = total_price + price;
       }
       if(Adai.isSelected()){
        double quantity = Double.parseDouble(AdaiQuantity.getValue().toString());
        double Adaiprice = 60;
        double price = quantity*Adaiprice;
        total_price = total_price + price;
       }
        if(SambarIdly.isSelected()){
        double quantity = Double.parseDouble(SambarIdlyQuantity.getValue().toString());
        double SambarIdlyprice = 60;
        double price = quantity*SambarIdlyprice;
        total_price = total_price + price;
       }
         if(PodiDosa.isSelected()){
        double quantity = Double.parseDouble(PodiDosaQuantity.getValue().toString());
        double PodiDosaprice = 80;
        double price = quantity*PodiDosaprice;
        total_price = total_price + price;
       }
          if(Pongal.isSelected()){
        double quantity = Double.parseDouble(PongalQuantity.getValue().toString());
        double Pongalprice = 70;
        double price = quantity*Pongalprice;
        total_price = total_price + price;
       }
          if(Puliyodharai.isSelected()){
        double quantity = Double.parseDouble(PuliyodharaiQuantity.getValue().toString());
        double Puliyodharaiprice = 50;
        double price = quantity*Puliyodharaiprice;
        total_price = total_price + price;
       }
          if(MealMakerBiriyani.isSelected()){
        double quantity = Double.parseDouble(MealMakerBiriyaniQuantity.getValue().toString());
        double MealMakerBiriyaniprice = 70;
        double price = quantity*MealMakerBiriyaniprice;
        total_price = total_price + price;
       }
         if(ComboMeals.isSelected()){
        double quantity = Double.parseDouble(ComboMealsQuantity.getValue().toString());
        double ComboMealsprice = 150;
        double price = quantity*ComboMealsprice;
        total_price = total_price + price;
       }
         if(FullMeals.isSelected()){
        double quantity = Double.parseDouble(FullMealsQuantity.getValue().toString());
        double FullMealsprice = 100;
        double price = quantity*FullMealsprice;
        total_price = total_price + price;
       }
          if(BabyMeals.isSelected()){
        double quantity = Double.parseDouble(BabyMealsQuantity.getValue().toString());
        double BabyMealsprice = 60;
        double price = quantity*BabyMealsprice;
        total_price = total_price + price;
       }
           if(AlooParotta.isSelected()){
        double quantity = Double.parseDouble(AlooParottaQuantity.getValue().toString());
        double AlooParottaprice = 90;
        double price = quantity*AlooParottaprice;
        total_price = total_price + price;
       }
            if(SchezwanNoodles.isSelected()){
        double quantity = Double.parseDouble(SchezwanNoodlesQuantity.getValue().toString());
        double SchezwanNoodlesprice = 100;
        double price = quantity*SchezwanNoodlesprice;
        total_price = total_price + price;
       }
             if(VegNuggets.isSelected()){
        double quantity = Double.parseDouble(VegNuggetsQuantity.getValue().toString());
        double VegNuggetsprice = 70;
        double price = quantity*VegNuggetsprice;
        total_price = total_price + price;
       }
              if(RumaliRoti.isSelected()){
        double quantity = Double.parseDouble(RumaliRotiQuantity.getValue().toString());
        double RumaliRotiprice = 90;
        double price = quantity*RumaliRotiprice;
        total_price = total_price + price;
       }
               if(Pasta.isSelected()){
        double quantity = Double.parseDouble(PastaQuantity.getValue().toString());
        double Pastaprice = 70;
        double price = quantity*Pastaprice;
        total_price = total_price + price;
       }
         
       TotalPrice.setText(""+total_price);
          
    }//GEN-LAST:event_TotalButtonActionPerformed

    private void PuliyodharaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuliyodharaiActionPerformed
         double quantity = Double.parseDouble(PuliyodharaiQuantity.getValue().toString());
         double Puliyodharaiprice = 50;
        if(Puliyodharai.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Puliyodharai.getText()+"; ");
         double price = quantity*Puliyodharaiprice;
         OrderSum.append("Quantity :"+PuliyodharaiQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
           
        }
    }//GEN-LAST:event_PuliyodharaiActionPerformed

    private void MealMakerBiriyaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealMakerBiriyaniActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(MealMakerBiriyaniQuantity.getValue().toString());
         double mmb_price = 70;
        if(MealMakerBiriyani.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+MealMakerBiriyani.getText()+"; ");
         double price = quantity*mmb_price;
         OrderSum.append("Quantity :"+MealMakerBiriyaniQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_MealMakerBiriyaniActionPerformed

    private void ComboMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMealsActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(ComboMealsQuantity.getValue().toString());
         double ComboMealsprice = 150;
        if(ComboMeals.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+ComboMeals.getText()+"; ");
         double price = quantity*ComboMealsprice;
         OrderSum.append("Quantity :"+ComboMealsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_ComboMealsActionPerformed

    private void FullMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullMealsActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(FullMealsQuantity.getValue().toString());
         double fm_price = 100;
        if(FullMeals.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+FullMeals.getText()+"; ");
         double price = quantity*fm_price;
         OrderSum.append("Quantity :"+FullMealsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_FullMealsActionPerformed

    private void BabyMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BabyMealsActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(BabyMealsQuantity.getValue().toString());
         double bm_price = 60;
        if(BabyMeals.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+BabyMeals.getText()+"; ");
         double price = quantity*bm_price;
         OrderSum.append("Quantity :"+BabyMealsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_BabyMealsActionPerformed

    private void AlooParottaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlooParottaActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(AlooParottaQuantity.getValue().toString());
         double AlooParottaprice = 90;
        if(AlooParotta.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+AlooParotta.getText()+"; ");
         double price = quantity*AlooParottaprice;
         OrderSum.append("Quantity :"+AlooParottaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_AlooParottaActionPerformed

    private void SchezwanNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchezwanNoodlesActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(SchezwanNoodlesQuantity.getValue().toString());
         double s_noodlesprice = 100;
        if(SchezwanNoodles.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+SchezwanNoodles.getText()+"; ");
         double price = quantity*s_noodlesprice;
         OrderSum.append("Quantity :"+SchezwanNoodlesQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_SchezwanNoodlesActionPerformed

    private void VegNuggetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegNuggetsActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(VegNuggetsQuantity.getValue().toString());
         double VegNuggetsprice = 70;
        if(VegNuggets.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+VegNuggets.getText()+"; ");
         double price = quantity*VegNuggetsprice;
         OrderSum.append("Quantity :"+VegNuggetsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_VegNuggetsActionPerformed

    private void RumaliRotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RumaliRotiActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(RumaliRotiQuantity.getValue().toString());
         double r_rotiprice = 90;
        if(RumaliRoti.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+RumaliRoti.getText()+"; ");
         double price = quantity*r_rotiprice;
         OrderSum.append("Quantity :"+RumaliRotiQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_RumaliRotiActionPerformed

    private void PastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(PastaQuantity.getValue().toString());
         double Pastaprice = 70;
        if(Pasta.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Pasta.getText()+"; ");
         double price = quantity*Pastaprice;
         OrderSum.append("Quantity :"+PastaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PastaActionPerformed

    private void mjn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mjn
        // TODO add your handling code here:
    }//GEN-LAST:event_mjn

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame();
        double Total = Double.parseDouble(TotalPrice.getText());
        if(PromoCode.getText().equals("DIWALI20")){
           double Disc_Amount = Total-(Total*0.3);
           TotalPrice.setText(""+Disc_Amount);
        }
        else{
        JOptionPane.showMessageDialog(f,"Enter a valid code");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void FigShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FigShakeActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(FigShakeQuantity.getValue().toString());
         double FigShakeprice = 150;
        if(FigShake.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+FigShake.getText()+"; ");
         double price = quantity*FigShakeprice;
         OrderSum.append("Quantity :"+FigShakeQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_FigShakeActionPerformed

    private void LimeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimeJuiceActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(LimeJuiceQuantity.getValue().toString());
         double LimeJuiceprice = 50;
        if(LimeJuice.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+LimeJuice.getText()+"; ");
         double price = quantity*LimeJuiceprice;
         OrderSum.append("Quantity :"+LimeJuiceQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_LimeJuiceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         OnlinePayment OP = new OnlinePayment();
        OP.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant_a2b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant_a2b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant_a2b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant_a2b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant_a2b().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Adai;
    private javax.swing.JSpinner AdaiQuantity;
    private javax.swing.JCheckBox AlooParotta;
    private javax.swing.JSpinner AlooParottaQuantity;
    private javax.swing.JCheckBox BabyMeals;
    private javax.swing.JSpinner BabyMealsQuantity;
    private javax.swing.JCheckBox ComboMeals;
    private javax.swing.JSpinner ComboMealsQuantity;
    private javax.swing.JCheckBox Falooda;
    private javax.swing.JSpinner FaloodaQuantity;
    private javax.swing.JCheckBox FigShake;
    private javax.swing.JSpinner FigShakeQuantity;
    private javax.swing.JCheckBox FullMeals;
    private javax.swing.JSpinner FullMealsQuantity;
    private javax.swing.JCheckBox LimeJuice;
    private javax.swing.JSpinner LimeJuiceQuantity;
    private javax.swing.JCheckBox MasalDosa;
    private javax.swing.JSpinner MasalDosaQuantity;
    private javax.swing.JCheckBox MealMakerBiriyani;
    private javax.swing.JSpinner MealMakerBiriyaniQuantity;
    private javax.swing.JTextArea OrderSum;
    private javax.swing.JCheckBox Pasta;
    private javax.swing.JSpinner PastaQuantity;
    private javax.swing.JCheckBox PodiDosa;
    private javax.swing.JSpinner PodiDosaQuantity;
    private javax.swing.JCheckBox Pongal;
    private javax.swing.JSpinner PongalQuantity;
    private javax.swing.JTextField PromoCode;
    private javax.swing.JCheckBox Puliyodharai;
    private javax.swing.JSpinner PuliyodharaiQuantity;
    private javax.swing.JCheckBox RumaliRoti;
    private javax.swing.JSpinner RumaliRotiQuantity;
    private javax.swing.JCheckBox SambarIdly;
    private javax.swing.JSpinner SambarIdlyQuantity;
    private javax.swing.JCheckBox SchezwanNoodles;
    private javax.swing.JSpinner SchezwanNoodlesQuantity;
    private javax.swing.JButton TotalButton;
    private javax.swing.JTextField TotalPrice;
    private javax.swing.JCheckBox VegNuggets;
    private javax.swing.JSpinner VegNuggetsQuantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private String String(int price) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
