/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddelivery;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vasanth
 */
public class Restaurant_Amman extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant_Anjappar
     */
    public Restaurant_Amman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        Pongal = new javax.swing.JCheckBox();
        ChilliIdly = new javax.swing.JCheckBox();
        PaperRoastDosa = new javax.swing.JCheckBox();
        Chappathi = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PongalQuantity = new javax.swing.JSpinner();
        ChilliIdlyQuantity = new javax.swing.JSpinner();
        PaperRoastDosaQuantity = new javax.swing.JSpinner();
        ChappathiQuantity = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FullMeals = new javax.swing.JCheckBox();
        BabyMeals = new javax.swing.JCheckBox();
        TomatoRice = new javax.swing.JCheckBox();
        VegBiriyani = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        FullMealsQuantity = new javax.swing.JSpinner();
        BabyMealsQuantity = new javax.swing.JSpinner();
        TomatoRiceQuantity = new javax.swing.JSpinner();
        VegBiriyaniQuantity = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        MushroomFriedRice = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        PanneerNoodles = new javax.swing.JCheckBox();
        KalDosa = new javax.swing.JCheckBox();
        PanneerButterMasala = new javax.swing.JCheckBox();
        ButterNaan = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        MushroomFriedRiceQuantity = new javax.swing.JSpinner();
        PanneerNoodlesQuantity = new javax.swing.JSpinner();
        KalDosaQuantity = new javax.swing.JSpinner();
        PanneerButterMasalaQuantity = new javax.swing.JSpinner();
        ButterNaanQuantity = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        Mojito = new javax.swing.JCheckBox();
        OreoShake = new javax.swing.JCheckBox();
        LimeJuice = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MojitoQuantity = new javax.swing.JSpinner();
        OreoShakeQuantity = new javax.swing.JSpinner();
        LimeJuiceQuantity = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderSum = new javax.swing.JTextArea();
        TotalPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TotalButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        PromoCode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mjn(evt);
            }
        });

        Pongal.setText("PONGAL-Rs 40");
        Pongal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PongalMouseClicked(evt);
            }
        });
        Pongal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PongalActionPerformed(evt);
            }
        });

        ChilliIdly.setText("CHILLI IDLY-Rs 50");
        ChilliIdly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChilliIdlyActionPerformed(evt);
            }
        });

        PaperRoastDosa.setText("PAPER ROAST DOSA Rs 70");
        PaperRoastDosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaperRoastDosaActionPerformed(evt);
            }
        });

        Chappathi.setText("CHAPPATHI Rs 40");
        Chappathi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChappathiActionPerformed(evt);
            }
        });

        jLabel4.setText("DISHES");

        jLabel5.setText("QUANTITY");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PaperRoastDosa)
                    .addComponent(ChilliIdly)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Pongal)
                        .addComponent(jLabel4))
                    .addComponent(Chappathi))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PaperRoastDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChappathiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PongalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChilliIdlyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(485, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pongal)
                    .addComponent(PongalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChilliIdly)
                    .addComponent(ChilliIdlyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaperRoastDosa)
                    .addComponent(PaperRoastDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chappathi)
                    .addComponent(ChappathiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BREAKFAST", jPanel7);

        jLabel1.setText("DISHES");

        FullMeals.setText("FULL MEALS-Rs 160");
        FullMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullMealsActionPerformed(evt);
            }
        });

        BabyMeals.setText("BABY MEALS Rs 120");
        BabyMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BabyMealsActionPerformed(evt);
            }
        });

        TomatoRice.setText("TOMOTA RICE Rs 60");
        TomatoRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TomatoRiceActionPerformed(evt);
            }
        });

        VegBiriyani.setText("VEG BIRIYANI Rs80");
        VegBiriyani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegBiriyaniActionPerformed(evt);
            }
        });

        jLabel2.setText("QUANTITY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(271, 271, 271)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FullMeals)
                            .addComponent(VegBiriyani)
                            .addComponent(TomatoRice)
                            .addComponent(BabyMeals))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BabyMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FullMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TomatoRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VegBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FullMeals)
                    .addComponent(FullMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BabyMeals)
                    .addComponent(BabyMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TomatoRice)
                    .addComponent(TomatoRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VegBiriyani)
                    .addComponent(VegBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LUNCH", jPanel1);

        MushroomFriedRice.setText("MUSHROOM FRIED RICE -Rs 120");
        MushroomFriedRice.setToolTipText("");
        MushroomFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MushroomFriedRiceActionPerformed(evt);
            }
        });

        jLabel6.setText("DISHES");

        PanneerNoodles.setText("PANNEER NOODLES -Rs 120");
        PanneerNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanneerNoodlesActionPerformed(evt);
            }
        });

        KalDosa.setText("KAL DOSA -Rs 65");
        KalDosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KalDosaActionPerformed(evt);
            }
        });

        PanneerButterMasala.setText("PANNEER BUTTER MASALA -Rs 90");
        PanneerButterMasala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanneerButterMasalaActionPerformed(evt);
            }
        });

        ButterNaan.setText("BUTTER NAAN -Rs 40");
        ButterNaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButterNaanActionPerformed(evt);
            }
        });

        jLabel7.setText("QUANTITY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanneerNoodles)
                            .addComponent(MushroomFriedRice)
                            .addComponent(KalDosa)
                            .addComponent(PanneerButterMasala)
                            .addComponent(ButterNaan))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanneerNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MushroomFriedRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KalDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanneerButterMasalaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButterNaanQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MushroomFriedRice)
                    .addComponent(MushroomFriedRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanneerNoodles)
                    .addComponent(PanneerNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KalDosa)
                    .addComponent(KalDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanneerButterMasala)
                    .addComponent(PanneerButterMasalaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButterNaan)
                    .addComponent(ButterNaanQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DINNER", jPanel3);

        Mojito.setText("MOJITO -Rs 75");
        Mojito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MojitoActionPerformed(evt);
            }
        });

        OreoShake.setText("OREO SHAKE -Rs 120");
        OreoShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OreoShakeActionPerformed(evt);
            }
        });

        LimeJuice.setText("LIME JUICE -Rs 50");
        LimeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimeJuiceActionPerformed(evt);
            }
        });

        jLabel8.setText("DISHES");

        jLabel9.setText("QUANTITY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mojito)
                            .addComponent(OreoShake)
                            .addComponent(LimeJuice))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OreoShakeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MojitoQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LimeJuiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mojito)
                    .addComponent(MojitoQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OreoShake)
                    .addComponent(OreoShakeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimeJuice)
                    .addComponent(LimeJuiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DESSERTS", jPanel4);

        OrderSum.setColumns(20);
        OrderSum.setRows(5);
        jScrollPane1.setViewportView(OrderSum);

        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });

        jLabel10.setText("DISHES ORDERED WITH THEIR PRICE");

        jButton1.setText("CASH ON DELIVERY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ONLINE PAYMENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TotalButton.setText("TOTAL");
        TotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("APPLY PROMO CODE");

        jButton3.setText("APPLY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel11)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(TotalPrice))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                                .addGap(124, 124, 124))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(TotalButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ORDER SUMMARY", jPanel2);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("AMMAN RESTAURANT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel3)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChilliIdlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChilliIdlyActionPerformed
        // TODO add your handling code here:
        
         double quantity = Double.parseDouble(ChilliIdlyQuantity.getValue().toString());
         double ChilliIdlyprice = 50;
        if(ChilliIdly.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+ChilliIdly.getText()+"; ");
         double price = quantity*ChilliIdlyprice;
         OrderSum.append("Quantity :"+ChilliIdlyQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_ChilliIdlyActionPerformed

    private void MojitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MojitoActionPerformed
        // TODO add your handling code here:
         
         double quantity = Double.parseDouble(MojitoQuantity.getValue().toString());
         double Mojitoprice = 75;
        if(Mojito.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Mojito.getText()+"; ");
         double price = quantity*Mojitoprice;
         OrderSum.append("Quantity :"+MojitoQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_MojitoActionPerformed

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         AddressInfo AI = new AddressInfo();
        AI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PongalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PongalMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_PongalMouseClicked

    private void PongalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PongalActionPerformed
        // TODO add your handling code here:
       
         double quantity = Double.parseDouble(PongalQuantity.getValue().toString());
         double Pongalprice = 40;
        if(Pongal.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Pongal.getText()+"; ");
         double price = quantity*Pongalprice;
         OrderSum.append("Quantity :"+PongalQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PongalActionPerformed

    private void PaperRoastDosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaperRoastDosaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(PaperRoastDosaQuantity.getValue().toString());
         double PaperRoastDosaprice = 70;
        if(PaperRoastDosa.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+PaperRoastDosa.getText()+"; ");
         double price = quantity*PaperRoastDosaprice;
         OrderSum.append("Quantity :"+PaperRoastDosaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PaperRoastDosaActionPerformed

    private void ChappathiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChappathiActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(ChappathiQuantity.getValue().toString());
         double Chappathiprice = 40;
          OrderSum.append("\n"+Chappathi.getText()+"; ");
            OrderSum.append("Quantity :"+ChappathiQuantity.getValue()
         +" ;");
        if(Chappathi.isSelected()){
           // double price = quantity*dosaprice;
        
         double price = quantity*Chappathiprice;
       
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_ChappathiActionPerformed

    private void TotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalButtonActionPerformed
        // TODO add your handling code here
       double total_price = 0;
       if(Pongal.isSelected()){
        double quantity = Double.parseDouble(PongalQuantity.getValue().toString());
        double Pongalprice = 40;
        double price = quantity*Pongalprice;
        total_price = total_price + price;
       }
       if(ChilliIdly.isSelected()){
        double quantity = Double.parseDouble(ChilliIdlyQuantity.getValue().toString());
        double ChilliIdlyprice = 50;
        double price = quantity*ChilliIdlyprice;
        total_price = total_price + price;
       }
        if(PaperRoastDosa.isSelected()){
        double quantity = Double.parseDouble(PaperRoastDosaQuantity.getValue().toString());
        double PaperRoastDosaprice = 70;
        double price = quantity*PaperRoastDosaprice;
        total_price = total_price + price;
       }
         if(Chappathi.isSelected()){
        double quantity = Double.parseDouble(ChappathiQuantity.getValue().toString());
        double Chappathiprice = 40;
        double price = quantity*Chappathiprice;
        total_price = total_price + price;
       }
          if(Pongal.isSelected()){
        double quantity = Double.parseDouble(PongalQuantity.getValue().toString());
        double Pongalprice = 40;
        double price = quantity*Pongalprice;
        total_price = total_price + price;
       }
          if(FullMeals.isSelected()){
        double quantity = Double.parseDouble(FullMealsQuantity.getValue().toString());
        double FullMealsprice = 160;
        double price = quantity*FullMealsprice;
        total_price = total_price + price;
       }
          if(BabyMeals.isSelected()){
        double quantity = Double.parseDouble(BabyMealsQuantity.getValue().toString());
        double BabyMealsprice = 120;
        double price = quantity*BabyMealsprice;
        total_price = total_price + price;
       }
         if(TomatoRice.isSelected()){
        double quantity = Double.parseDouble(TomatoRiceQuantity.getValue().toString());
        double TomatoRiceprice = 60;
        double price = quantity*TomatoRiceprice;
        total_price = total_price + price;
       }
         if(VegBiriyani.isSelected()){
        double quantity = Double.parseDouble(VegBiriyaniQuantity.getValue().toString());
        double VegBiriyaniprice = 80;
        double price = quantity*VegBiriyaniprice;
        total_price = total_price + price;
       }
          if(BabyMeals.isSelected()){
        double quantity = Double.parseDouble(BabyMealsQuantity.getValue().toString());
        double BabyMealsprice = 60;
        double price = quantity*BabyMealsprice;
        total_price = total_price + price;
       }
           if(MushroomFriedRice.isSelected()){
        double quantity = Double.parseDouble(MushroomFriedRiceQuantity.getValue().toString());
        double MushroomFriedRiceprice = 120;
        double price = quantity*MushroomFriedRiceprice;
        total_price = total_price + price;
       }
            if(PanneerNoodles.isSelected()){
        double quantity = Double.parseDouble(PanneerNoodlesQuantity.getValue().toString());
        double PanneerNoodlesprice = 120;
        double price = quantity*PanneerNoodlesprice;
        total_price = total_price + price;
       }
             if(KalDosa.isSelected()){
        double quantity = Double.parseDouble(KalDosaQuantity.getValue().toString());
        double KalDosaprice = 70 - 5;
        double price = quantity*KalDosaprice;
        total_price = total_price + price;
       }
              if(PanneerButterMasala.isSelected()){
        double quantity = Double.parseDouble(PanneerButterMasalaQuantity.getValue().toString());
        double PanneerButterMasalaprice = 90;
        double price = quantity*PanneerButterMasalaprice;
        total_price = total_price + price;
       }
               if(ButterNaan.isSelected()){
        double quantity = Double.parseDouble(ButterNaanQuantity.getValue().toString());
        double ButterNaanprice = 40;
        double price = quantity*ButterNaanprice;
        total_price = total_price + price;
       }
        if(Mojito.isSelected()){
        double quantity = Double.parseDouble(MojitoQuantity.getValue().toString());
        double Mojitoprice = 75;
        double price = quantity*Mojitoprice;
        total_price = total_price + price;
       }
         if(OreoShake.isSelected()){
            double quantity = Double.parseDouble(OreoShakeQuantity.getValue().toString());
            double OreoShakeprice = 150;
            double price = quantity*OreoShakeprice;
            total_price = total_price + price;
         }
          if(LimeJuice.isSelected()){
            double quantity = Double.parseDouble(LimeJuiceQuantity.getValue().toString());
            double LimeJuiceprice = 50;
            double price = quantity*LimeJuiceprice;
            total_price = total_price + price;
         }
        
       TotalPrice.setText(""+total_price);
          
    }//GEN-LAST:event_TotalButtonActionPerformed

    private void FullMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullMealsActionPerformed
         double quantity = Double.parseDouble(FullMealsQuantity.getValue().toString());
         double FullMealsprice = 160;
        if(FullMeals.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+FullMeals.getText()+"; ");
         double price = quantity*FullMealsprice;
         OrderSum.append("Quantity :"+FullMealsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
           
        }
    }//GEN-LAST:event_FullMealsActionPerformed

    private void BabyMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BabyMealsActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(BabyMealsQuantity.getValue().toString());
         double BabyMealsprice = 120;
        if(BabyMeals.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+BabyMeals.getText()+"; ");
         double price = quantity*BabyMealsprice;
         OrderSum.append("Quantity :"+BabyMealsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_BabyMealsActionPerformed

    private void TomatoRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TomatoRiceActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(TomatoRiceQuantity.getValue().toString());
         double TomatoRiceprice = 60;
        if(TomatoRice.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+TomatoRice.getText()+"; ");
         double price = quantity*TomatoRiceprice;
         OrderSum.append("Quantity :"+TomatoRiceQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_TomatoRiceActionPerformed

    private void VegBiriyaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegBiriyaniActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(VegBiriyaniQuantity.getValue().toString());
         double VegBiriyaniprice = 80;
        if(VegBiriyani.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+VegBiriyani.getText()+"; ");
         double price = quantity*VegBiriyaniprice;
         OrderSum.append("Quantity :"+VegBiriyaniQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_VegBiriyaniActionPerformed

    private void MushroomFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MushroomFriedRiceActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(MushroomFriedRiceQuantity.getValue().toString());
         double MushroomFriedRiceprice = 120;
        if(MushroomFriedRice.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+MushroomFriedRice.getText()+"; ");
         double price = quantity*MushroomFriedRiceprice;
         OrderSum.append("Quantity :"+MushroomFriedRiceQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_MushroomFriedRiceActionPerformed

    private void PanneerNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanneerNoodlesActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(PanneerNoodlesQuantity.getValue().toString());
         double p_noodlesprice = 120;
        if(PanneerNoodles.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+PanneerNoodles.getText()+"; ");
         double price = quantity*p_noodlesprice;
         OrderSum.append("Quantity :"+PanneerNoodlesQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PanneerNoodlesActionPerformed

    private void KalDosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KalDosaActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(KalDosaQuantity.getValue().toString());
         double KalDosaprice = 70-5;
        if(KalDosa.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+KalDosa.getText()+"; ");
         double price = quantity*KalDosaprice;
         OrderSum.append("Quantity :"+KalDosaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_KalDosaActionPerformed

    private void PanneerButterMasalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanneerButterMasalaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(PanneerButterMasalaQuantity.getValue().toString());
         double PanneerButterMasalaprice = 90;
        if(PanneerButterMasala.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+PanneerButterMasala.getText()+"; ");
         double price = quantity*PanneerButterMasalaprice;
         OrderSum.append("Quantity :"+PanneerButterMasalaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PanneerButterMasalaActionPerformed

    private void ButterNaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButterNaanActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(ButterNaanQuantity.getValue().toString());
         double ButterNaanprice = 40;
        if(ButterNaan.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+ButterNaan.getText()+"; ");
         double price = quantity*ButterNaanprice;
         OrderSum.append("Quantity :"+ButterNaanQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_ButterNaanActionPerformed

    private void mjn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mjn
        // TODO add your handling code here:
    }//GEN-LAST:event_mjn

    private void OreoShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OreoShakeActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(OreoShakeQuantity.getValue().toString());
         double OreoShakeprice = 120;
        if(OreoShake.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+OreoShake.getText()+"; ");
         double price = quantity*OreoShakeprice;
         OrderSum.append("Quantity :"+OreoShakeQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_OreoShakeActionPerformed

    private void LimeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimeJuiceActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(LimeJuiceQuantity.getValue().toString());
        double LimeJuiceprice = 50;
        if(LimeJuice.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+LimeJuice.getText()+"; ");
         double price = quantity*LimeJuiceprice;
         OrderSum.append("Quantity :"+LimeJuiceQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
         
        }
    }//GEN-LAST:event_LimeJuiceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         JFrame f = new JFrame();
        double Total = Double.parseDouble(TotalPrice.getText());
        if(PromoCode.getText().equals("DIWALI20")){
           double Disc_Amount = Total-(Total*0.3);
           TotalPrice.setText(""+Disc_Amount);
        }
        else{
        JOptionPane.showMessageDialog(f,"Enter a valid code");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         OnlinePayment OP = new OnlinePayment();
        OP.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Amman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Amman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Amman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Amman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant_Amman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BabyMeals;
    private javax.swing.JSpinner BabyMealsQuantity;
    private javax.swing.JCheckBox ButterNaan;
    private javax.swing.JSpinner ButterNaanQuantity;
    private javax.swing.JCheckBox Chappathi;
    private javax.swing.JSpinner ChappathiQuantity;
    private javax.swing.JCheckBox ChilliIdly;
    private javax.swing.JSpinner ChilliIdlyQuantity;
    private javax.swing.JCheckBox FullMeals;
    private javax.swing.JSpinner FullMealsQuantity;
    private javax.swing.JCheckBox KalDosa;
    private javax.swing.JSpinner KalDosaQuantity;
    private javax.swing.JCheckBox LimeJuice;
    private javax.swing.JSpinner LimeJuiceQuantity;
    private javax.swing.JCheckBox Mojito;
    private javax.swing.JSpinner MojitoQuantity;
    private javax.swing.JCheckBox MushroomFriedRice;
    private javax.swing.JSpinner MushroomFriedRiceQuantity;
    private javax.swing.JTextArea OrderSum;
    private javax.swing.JCheckBox OreoShake;
    private javax.swing.JSpinner OreoShakeQuantity;
    private javax.swing.JCheckBox PanneerButterMasala;
    private javax.swing.JSpinner PanneerButterMasalaQuantity;
    private javax.swing.JCheckBox PanneerNoodles;
    private javax.swing.JSpinner PanneerNoodlesQuantity;
    private javax.swing.JCheckBox PaperRoastDosa;
    private javax.swing.JSpinner PaperRoastDosaQuantity;
    private javax.swing.JCheckBox Pongal;
    private javax.swing.JSpinner PongalQuantity;
    private javax.swing.JTextField PromoCode;
    private javax.swing.JCheckBox TomatoRice;
    private javax.swing.JSpinner TomatoRiceQuantity;
    private javax.swing.JButton TotalButton;
    private javax.swing.JTextField TotalPrice;
    private javax.swing.JCheckBox VegBiriyani;
    private javax.swing.JSpinner VegBiriyaniQuantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private String String(int price) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
