/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddelivery;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vasanth
 */
public class Restaurant_Amsavalli extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant_Amsavalli
     */
    public Restaurant_Amsavalli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        Appam = new javax.swing.JCheckBox();
        PodiIdly = new javax.swing.JCheckBox();
        RavaIdly = new javax.swing.JCheckBox();
        GheeRoastDosa = new javax.swing.JCheckBox();
        Pongal = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AppamQuantity = new javax.swing.JSpinner();
        PodiIdlyQuantity = new javax.swing.JSpinner();
        RavaIdlyQuantity = new javax.swing.JSpinner();
        GheeRoastDosaQuantity = new javax.swing.JSpinner();
        PongalQuantity = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FullMeals = new javax.swing.JCheckBox();
        CurdRice = new javax.swing.JCheckBox();
        TomatoFriedRice = new javax.swing.JCheckBox();
        VegBiriyani = new javax.swing.JCheckBox();
        BabyMeals = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        FullMealsQuantity = new javax.swing.JSpinner();
        CurdRiceQuantity = new javax.swing.JSpinner();
        TomatoFriedRiceQuantity = new javax.swing.JSpinner();
        VegBiriyaniQuantity = new javax.swing.JSpinner();
        BabyMealsQuantity = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        MushroomNoodles = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        FriedNoodles = new javax.swing.JCheckBox();
        VegKothuParotta = new javax.swing.JCheckBox();
        WheatParotta = new javax.swing.JCheckBox();
        ChilliParotta = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        MushroomNoodlesQuantity = new javax.swing.JSpinner();
        FriedNoodlesQuantity = new javax.swing.JSpinner();
        VegKothuParottaQuantity = new javax.swing.JSpinner();
        WheatParottaQuantity = new javax.swing.JSpinner();
        ChilliParottaQuantity = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        IceCreamShake = new javax.swing.JCheckBox();
        MilkShake = new javax.swing.JCheckBox();
        LimeJuice = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IceCreamShakeQuantity = new javax.swing.JSpinner();
        MilkShakeQuantity = new javax.swing.JSpinner();
        LimeJuiceQuantity = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderSum = new javax.swing.JTextArea();
        TotalPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TotalButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        PromoCode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mjn(evt);
            }
        });

        Appam.setText("APPAM -Rs 40");
        Appam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppamMouseClicked(evt);
            }
        });
        Appam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppamActionPerformed(evt);
            }
        });

        PodiIdly.setText("PODI IDLY-Rs 30");
        PodiIdly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PodiIdlyActionPerformed(evt);
            }
        });

        RavaIdly.setText("RAVA IDLY Rs 40");
        RavaIdly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RavaIdlyActionPerformed(evt);
            }
        });

        GheeRoastDosa.setText("GHEE ROAST DOSA Rs 90");
        GheeRoastDosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GheeRoastDosaActionPerformed(evt);
            }
        });

        Pongal.setText("PONGAL -Rs 70");
        Pongal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PongalActionPerformed(evt);
            }
        });

        jLabel4.setText("DISHES");

        jLabel5.setText("QUANTITY");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(GheeRoastDosa)
                        .addComponent(RavaIdly, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PodiIdly, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Pongal, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Appam)
                        .addComponent(jLabel4)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PongalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RavaIdlyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GheeRoastDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AppamQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PodiIdlyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(491, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Appam)
                    .addComponent(AppamQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PodiIdly)
                    .addComponent(PodiIdlyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RavaIdly)
                    .addComponent(RavaIdlyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GheeRoastDosa)
                    .addComponent(GheeRoastDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pongal)
                    .addComponent(PongalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BREAKFAST", jPanel7);

        jLabel1.setText("DISHES");

        FullMeals.setText("FULL MEALS -Rs 130");
        FullMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullMealsActionPerformed(evt);
            }
        });

        CurdRice.setText("CURD RICE Rs 60");
        CurdRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurdRiceActionPerformed(evt);
            }
        });

        TomatoFriedRice.setText("TOMATO FRIED RICE Rs 100");
        TomatoFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TomatoFriedRiceActionPerformed(evt);
            }
        });

        VegBiriyani.setText("VEG BIRIYANI Rs 100");
        VegBiriyani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegBiriyaniActionPerformed(evt);
            }
        });

        BabyMeals.setText("BABY MEALS Rs 90");
        BabyMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BabyMealsActionPerformed(evt);
            }
        });

        jLabel2.setText("QUANTITY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(271, 271, 271)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FullMeals)
                            .addComponent(VegBiriyani)
                            .addComponent(BabyMeals)
                            .addComponent(TomatoFriedRice)
                            .addComponent(CurdRice))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CurdRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FullMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TomatoFriedRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VegBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BabyMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FullMeals)
                    .addComponent(FullMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurdRice)
                    .addComponent(CurdRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TomatoFriedRice)
                    .addComponent(TomatoFriedRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VegBiriyani)
                    .addComponent(VegBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BabyMeals)
                    .addComponent(BabyMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LUNCH", jPanel1);

        MushroomNoodles.setText("MUSHROOM NOODLES -Rs 90");
        MushroomNoodles.setToolTipText("");
        MushroomNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MushroomNoodlesActionPerformed(evt);
            }
        });

        jLabel6.setText("DISHES");

        FriedNoodles.setText("FRIED NOODLES -Rs 100");
        FriedNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriedNoodlesActionPerformed(evt);
            }
        });

        VegKothuParotta.setText("VEG KOTHU PAROTTA-Rs 100");
        VegKothuParotta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegKothuParottaActionPerformed(evt);
            }
        });

        WheatParotta.setText("WHEAT PAROTTA-Rs 50");
        WheatParotta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WheatParottaActionPerformed(evt);
            }
        });

        ChilliParotta.setText("CHILLI PAROTTA -Rs 80");
        ChilliParotta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChilliParottaActionPerformed(evt);
            }
        });

        jLabel7.setText("QUANTITY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FriedNoodles)
                            .addComponent(MushroomNoodles)
                            .addComponent(VegKothuParotta)
                            .addComponent(WheatParotta)
                            .addComponent(ChilliParotta))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FriedNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MushroomNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VegKothuParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WheatParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChilliParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MushroomNoodles)
                    .addComponent(MushroomNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FriedNoodles)
                    .addComponent(FriedNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VegKothuParotta)
                    .addComponent(VegKothuParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WheatParotta)
                    .addComponent(WheatParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChilliParotta)
                    .addComponent(ChilliParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DINNER", jPanel3);

        IceCreamShake.setText("ICE CREAM SHAKE-Rs 70");
        IceCreamShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IceCreamShakeActionPerformed(evt);
            }
        });

        MilkShake.setText("MILK SHAKE -Rs 50");
        MilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkShakeActionPerformed(evt);
            }
        });

        LimeJuice.setText("LIME JUICE -Rs 30");
        LimeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimeJuiceActionPerformed(evt);
            }
        });

        jLabel8.setText("DISHES");

        jLabel9.setText("QUANTITY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IceCreamShake)
                            .addComponent(MilkShake)
                            .addComponent(LimeJuice))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MilkShakeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IceCreamShakeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LimeJuiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(447, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IceCreamShake)
                    .addComponent(IceCreamShakeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MilkShake)
                    .addComponent(MilkShakeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimeJuice)
                    .addComponent(LimeJuiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DESSERTS", jPanel4);

        OrderSum.setColumns(20);
        OrderSum.setRows(5);
        jScrollPane1.setViewportView(OrderSum);

        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });

        jLabel10.setText("DISHES ORDERED WITH THEIR PRICE");

        jButton1.setText("CASH ON DELIVERY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ONLINE PAYMENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TotalButton.setText("TOTAL");
        TotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("APPLY PROMOCODE");

        jButton3.setText("APPLY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(TotalPrice))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                                .addGap(124, 124, 124))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(TotalButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ORDER SUMMARY", jPanel2);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("AMSAVALLI RESTAURANT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PodiIdlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PodiIdlyActionPerformed
        // TODO add your handling code here:
        
         double quantity = Double.parseDouble(PodiIdlyQuantity.getValue().toString());
         double PodiIdlyprice = 30;
        if(PodiIdly.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+PodiIdly.getText()+"; ");
         double price = quantity*PodiIdlyprice;
         OrderSum.append("Quantity :"+PodiIdlyQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PodiIdlyActionPerformed

    private void IceCreamShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IceCreamShakeActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(IceCreamShakeQuantity.getValue().toString());
         double IceCreamShakeprice = 70;
        if(IceCreamShake.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+IceCreamShake.getText()+"; ");
         double price = quantity*IceCreamShakeprice;
         OrderSum.append("Quantity :"+IceCreamShakeQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_IceCreamShakeActionPerformed

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         AddressInfo AI = new AddressInfo();
        AI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AppamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppamMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_AppamMouseClicked

    private void AppamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppamActionPerformed
        // TODO add your handling code here:
       
         double quantity = Double.parseDouble(AppamQuantity.getValue().toString());
         double Appamprice = 40;
        if(Appam.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Appam.getText()+"; ");
         double price = quantity*Appamprice;
         OrderSum.append("Quantity :"+AppamQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_AppamActionPerformed

    private void PongalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PongalActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(PongalQuantity.getValue().toString());
         double pongalprice = 70;
        if(Pongal.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Pongal.getText()+"; ");
         double price = quantity*pongalprice;
         OrderSum.append("Quantity :"+PongalQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PongalActionPerformed

    private void RavaIdlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RavaIdlyActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(RavaIdlyQuantity.getValue().toString());
         double RavaIdlyprice = 40;
        if(RavaIdly.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+RavaIdly.getText()+"; ");
         double price = quantity*RavaIdlyprice;
         OrderSum.append("Quantity :"+RavaIdlyQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_RavaIdlyActionPerformed

    private void GheeRoastDosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GheeRoastDosaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(GheeRoastDosaQuantity.getValue().toString());
         double GheeRoastDosaprice = 90;
          OrderSum.append("\n"+GheeRoastDosa.getText()+"; ");
            OrderSum.append("Quantity :"+GheeRoastDosaQuantity.getValue()
         +" ;");
        if(GheeRoastDosa.isSelected()){
           // double price = quantity*dosaprice;
        
         double price = quantity*GheeRoastDosaprice;
       
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_GheeRoastDosaActionPerformed

    private void TotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalButtonActionPerformed
        // TODO add your handling code here
       double total_price = 0;
        if(LimeJuice.isSelected()){
            double quantity = Double.parseDouble(LimeJuiceQuantity.getValue().toString());
            double LimeJuiceprice = 50;
            double price = quantity*LimeJuiceprice;
            total_price = total_price + price;
         }
         if(IceCreamShake.isSelected()){
            double quantity = Double.parseDouble(IceCreamShakeQuantity.getValue().toString());
            double IceCreamShakeprice = 70;
            double price = quantity*IceCreamShakeprice;
            total_price = total_price + price;
         }
         if(MilkShake.isSelected()){
            double quantity = Double.parseDouble(MilkShakeQuantity.getValue().toString());
            double MilkShakeprice = 50;
            double price = quantity*MilkShakeprice;
            total_price = total_price + price;
         }
       if(Appam.isSelected()){
        double quantity = Double.parseDouble(AppamQuantity.getValue().toString());
        double Appamprice = 40;
        double price = quantity*Appamprice;
        total_price = total_price + price;
       }
       if(PodiIdly.isSelected()){
        double quantity = Double.parseDouble(PodiIdlyQuantity.getValue().toString());
        double PodiIdlyprice = 30;
        double price = quantity*PodiIdlyprice;
        total_price = total_price + price;
       }
        if(RavaIdly.isSelected()){
        double quantity = Double.parseDouble(RavaIdlyQuantity.getValue().toString());
        double RavaIdlyprice = 40;
        double price = quantity*RavaIdlyprice;
        total_price = total_price + price;
       }
         if(GheeRoastDosa.isSelected()){
        double quantity = Double.parseDouble(GheeRoastDosaQuantity.getValue().toString());
        double GheeRoastDosaprice = 90;
        double price = quantity*GheeRoastDosaprice;
        total_price = total_price + price;
       }
          if(Pongal.isSelected()){
        double quantity = Double.parseDouble(PongalQuantity.getValue().toString());
        double Pongalprice = 70;
        double price = quantity*Pongalprice;
        total_price = total_price + price;
       }
          if(FullMeals.isSelected()){
        double quantity = Double.parseDouble(FullMealsQuantity.getValue().toString());
        double FullMealsprice = 130;
        double price = quantity*FullMealsprice;
        total_price = total_price + price;
       }
          if(CurdRice.isSelected()){
        double quantity = Double.parseDouble(CurdRiceQuantity.getValue().toString());
        double CurdRiceprice = 60;
        double price = quantity*CurdRiceprice;
        total_price = total_price + price;
       }
         if(TomatoFriedRice.isSelected()){
        double quantity = Double.parseDouble(TomatoFriedRiceQuantity.getValue().toString());
        double TomatoFriedRiceprice = 100;
        double price = quantity*TomatoFriedRiceprice;
        total_price = total_price + price;
       }
         if(VegBiriyani.isSelected()){
        double quantity = Double.parseDouble(VegBiriyaniQuantity.getValue().toString());
        double VegBiriyaniprice = 100;
        double price = quantity*VegBiriyaniprice;
        total_price = total_price + price;
       }
          if(BabyMeals.isSelected()){
        double quantity = Double.parseDouble(BabyMealsQuantity.getValue().toString());
        double BabyMealsprice = 90;
        double price = quantity*BabyMealsprice;
        total_price = total_price + price;
       }
           if(MushroomNoodles.isSelected()){
        double quantity = Double.parseDouble(MushroomNoodlesQuantity.getValue().toString());
        double MushroomNoodlesprice = 90;
        double price = quantity*MushroomNoodlesprice;
        total_price = total_price + price;
       }
            if(FriedNoodles.isSelected()){
        double quantity = Double.parseDouble(FriedNoodlesQuantity.getValue().toString());
        double FriedNoodlesprice = 100;
        double price = quantity*FriedNoodlesprice;
        total_price = total_price + price;
       }
             if(VegKothuParotta.isSelected()){
        double quantity = Double.parseDouble(VegKothuParottaQuantity.getValue().toString());
        double VegKothuParottaprice = 100;
        double price = quantity*VegKothuParottaprice;
        total_price = total_price + price;
       }
              if(WheatParotta.isSelected()){
        double quantity = Double.parseDouble(WheatParottaQuantity.getValue().toString());
        double WheatParottaprice = 50;
        double price = quantity*WheatParottaprice;
        total_price = total_price + price;
       }
               if(ChilliParotta.isSelected()){
        double quantity = Double.parseDouble(ChilliParottaQuantity.getValue().toString());
        double ChilliParottaprice = 80;
        double price = quantity*ChilliParottaprice;
        total_price = total_price + price;
       }
         
       TotalPrice.setText(""+total_price);
          
    }//GEN-LAST:event_TotalButtonActionPerformed

    private void FullMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullMealsActionPerformed
         double quantity = Double.parseDouble(FullMealsQuantity.getValue().toString());
         double FullMealsprice = 130;
        if(FullMeals.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+FullMeals.getText()+"; ");
         double price = quantity*FullMealsprice;
         OrderSum.append("Quantity :"+FullMealsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
           
        }
    }//GEN-LAST:event_FullMealsActionPerformed

    private void CurdRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurdRiceActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(CurdRiceQuantity.getValue().toString());
         double CurdRiceprice = 60;
        if(CurdRice.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+CurdRice.getText()+"; ");
         double price = quantity*CurdRiceprice;
         OrderSum.append("Quantity :"+CurdRiceQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_CurdRiceActionPerformed

    private void TomatoFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TomatoFriedRiceActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(TomatoFriedRiceQuantity.getValue().toString());
         double TomatoFriedRiceprice = 100;
        if(TomatoFriedRice.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+TomatoFriedRice.getText()+"; ");
         double price = quantity*TomatoFriedRiceprice;
         OrderSum.append("Quantity :"+TomatoFriedRiceQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_TomatoFriedRiceActionPerformed

    private void VegBiriyaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegBiriyaniActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(VegBiriyaniQuantity.getValue().toString());
         double VegBiriyaniprice = 100;
        if(VegBiriyani.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+VegBiriyani.getText()+"; ");
         double price = quantity*VegBiriyaniprice;
         OrderSum.append("Quantity :"+VegBiriyaniQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_VegBiriyaniActionPerformed

    private void BabyMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BabyMealsActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(BabyMealsQuantity.getValue().toString());
         double bm_price = 90;
        if(BabyMeals.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+BabyMeals.getText()+"; ");
         double price = quantity*bm_price;
         OrderSum.append("Quantity :"+BabyMealsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_BabyMealsActionPerformed

    private void MushroomNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MushroomNoodlesActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(MushroomNoodlesQuantity.getValue().toString());
         double MushroomNoodlesprice = 90;
        if(MushroomNoodles.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+MushroomNoodles.getText()+"; ");
         double price = quantity*MushroomNoodlesprice;
         OrderSum.append("Quantity :"+MushroomNoodlesQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_MushroomNoodlesActionPerformed

    private void FriedNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriedNoodlesActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(FriedNoodlesQuantity.getValue().toString());
         double FriedNoodlesprice = 100;
        if(FriedNoodles.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+FriedNoodles.getText()+"; ");
         double price = quantity*FriedNoodlesprice;
         OrderSum.append("Quantity :"+FriedNoodlesQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_FriedNoodlesActionPerformed

    private void VegKothuParottaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegKothuParottaActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(VegKothuParottaQuantity.getValue().toString());
         double VegKothuParottaprice = 100;
        if(VegKothuParotta.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+VegKothuParotta.getText()+"; ");
         double price = quantity*VegKothuParottaprice;
         OrderSum.append("Quantity :"+VegKothuParottaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_VegKothuParottaActionPerformed

    private void WheatParottaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WheatParottaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(WheatParottaQuantity.getValue().toString());
         double WheatParottaprice = 50;
        if(WheatParotta.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+WheatParotta.getText()+"; ");
         double price = quantity*WheatParottaprice;
         OrderSum.append("Quantity :"+WheatParottaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_WheatParottaActionPerformed

    private void ChilliParottaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChilliParottaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(ChilliParottaQuantity.getValue().toString());
         double ChilliParottaprice = 80;
        if(ChilliParotta.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+ChilliParotta.getText()+"; ");
         double price = quantity*ChilliParottaprice;
         OrderSum.append("Quantity :"+ChilliParottaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_ChilliParottaActionPerformed

    private void mjn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mjn
        // TODO add your handling code here:
    }//GEN-LAST:event_mjn

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         JFrame f = new JFrame();
        double Total = Double.parseDouble(TotalPrice.getText());
        if(PromoCode.getText().equals("DIWALI20")){
           double Disc_Amount = Total-(Total*0.3);
           TotalPrice.setText(""+Disc_Amount);
        }
        else{
        JOptionPane.showMessageDialog(f,"Enter a valid code");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void MilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkShakeActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(MilkShakeQuantity.getValue().toString());
         double MilkShakeprice = 50;
        if(MilkShake.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+MilkShake.getText()+"; ");
         double price = quantity*MilkShakeprice;
         OrderSum.append("Quantity :"+MilkShakeQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_MilkShakeActionPerformed

    private void LimeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimeJuiceActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(LimeJuiceQuantity.getValue().toString());
         double LimeJuiceprice = 30;
        if(LimeJuice.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+LimeJuice.getText()+"; ");
         double price = quantity*LimeJuiceprice;
         OrderSum.append("Quantity :"+LimeJuiceQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_LimeJuiceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         OnlinePayment OP = new OnlinePayment();
        OP.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Amsavalli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Amsavalli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Amsavalli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Amsavalli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant_Amsavalli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Appam;
    private javax.swing.JSpinner AppamQuantity;
    private javax.swing.JCheckBox BabyMeals;
    private javax.swing.JSpinner BabyMealsQuantity;
    private javax.swing.JCheckBox ChilliParotta;
    private javax.swing.JSpinner ChilliParottaQuantity;
    private javax.swing.JCheckBox CurdRice;
    private javax.swing.JSpinner CurdRiceQuantity;
    private javax.swing.JCheckBox FriedNoodles;
    private javax.swing.JSpinner FriedNoodlesQuantity;
    private javax.swing.JCheckBox FullMeals;
    private javax.swing.JSpinner FullMealsQuantity;
    private javax.swing.JCheckBox GheeRoastDosa;
    private javax.swing.JSpinner GheeRoastDosaQuantity;
    private javax.swing.JCheckBox IceCreamShake;
    private javax.swing.JSpinner IceCreamShakeQuantity;
    private javax.swing.JCheckBox LimeJuice;
    private javax.swing.JSpinner LimeJuiceQuantity;
    private javax.swing.JCheckBox MilkShake;
    private javax.swing.JSpinner MilkShakeQuantity;
    private javax.swing.JCheckBox MushroomNoodles;
    private javax.swing.JSpinner MushroomNoodlesQuantity;
    private javax.swing.JTextArea OrderSum;
    private javax.swing.JCheckBox PodiIdly;
    private javax.swing.JSpinner PodiIdlyQuantity;
    private javax.swing.JCheckBox Pongal;
    private javax.swing.JSpinner PongalQuantity;
    private javax.swing.JTextField PromoCode;
    private javax.swing.JCheckBox RavaIdly;
    private javax.swing.JSpinner RavaIdlyQuantity;
    private javax.swing.JCheckBox TomatoFriedRice;
    private javax.swing.JSpinner TomatoFriedRiceQuantity;
    private javax.swing.JButton TotalButton;
    private javax.swing.JTextField TotalPrice;
    private javax.swing.JCheckBox VegBiriyani;
    private javax.swing.JSpinner VegBiriyaniQuantity;
    private javax.swing.JCheckBox VegKothuParotta;
    private javax.swing.JSpinner VegKothuParottaQuantity;
    private javax.swing.JCheckBox WheatParotta;
    private javax.swing.JSpinner WheatParottaQuantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private String String(int price) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
