/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddelivery;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vasanth
 */
public class Restaurant_Sabareesh extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant_Sabareesh
     */
    public Restaurant_Sabareesh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        IdlyVada = new javax.swing.JCheckBox();
        MysoreMasalDosa = new javax.swing.JCheckBox();
        RavaDosa = new javax.swing.JCheckBox();
        OnionDosa = new javax.swing.JCheckBox();
        Pongal = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IdlyVadaQuantity = new javax.swing.JSpinner();
        MysoreMasalDosaQuantity = new javax.swing.JSpinner();
        RavaDosaQuantity = new javax.swing.JSpinner();
        OnionDosaQuantity = new javax.swing.JSpinner();
        PongalQuantity = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FullMeals = new javax.swing.JCheckBox();
        BABYMEALS = new javax.swing.JCheckBox();
        VegBiriyani = new javax.swing.JCheckBox();
        TomatoRice = new javax.swing.JCheckBox();
        LemonRice = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        FullMealsQuantity = new javax.swing.JSpinner();
        BabyMealsQuantity = new javax.swing.JSpinner();
        VegBiriyaniQuantity = new javax.swing.JSpinner();
        TomatoRiceQuantity = new javax.swing.JSpinner();
        LemonRiceQuantity = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        Uthappam = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        VegNoodles = new javax.swing.JCheckBox();
        Dosa = new javax.swing.JCheckBox();
        PanneerRoti = new javax.swing.JCheckBox();
        ChilliParotta = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        UthappamQuantity = new javax.swing.JSpinner();
        VegNoodlesQuantity = new javax.swing.JSpinner();
        DosaQuantity = new javax.swing.JSpinner();
        PanneerRotiQuantity = new javax.swing.JSpinner();
        ChilliParottaQuantity = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        Falooda = new javax.swing.JCheckBox();
        VirginMary = new javax.swing.JCheckBox();
        LimeJuice = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FaloodaQuantity = new javax.swing.JSpinner();
        VirginMaryQuantity = new javax.swing.JSpinner();
        LimeJuiceQuantity = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderSum = new javax.swing.JTextArea();
        TotalPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TotalButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        PromoCode = new javax.swing.JTextField();
        Apply = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mjn(evt);
            }
        });

        IdlyVada.setText("VADA + IDLY -Rs 40");
        IdlyVada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IdlyVadaMouseClicked(evt);
            }
        });
        IdlyVada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdlyVadaActionPerformed(evt);
            }
        });

        MysoreMasalDosa.setText("MYSORE MASAL DOSA -Rs 90");
        MysoreMasalDosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MysoreMasalDosaActionPerformed(evt);
            }
        });

        RavaDosa.setText("RAVA DOSA Rs 60");
        RavaDosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RavaDosaActionPerformed(evt);
            }
        });

        OnionDosa.setText("ONION DOSA Rs 90");
        OnionDosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnionDosaActionPerformed(evt);
            }
        });

        Pongal.setText("PONGAL -Rs 70");
        Pongal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PongalActionPerformed(evt);
            }
        });

        jLabel4.setText("DISHES");

        jLabel5.setText("QUANTITY");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RavaDosa)
                    .addComponent(MysoreMasalDosa)
                    .addComponent(Pongal)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(IdlyVada)
                        .addComponent(jLabel4))
                    .addComponent(OnionDosa))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PongalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RavaDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OnionDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdlyVadaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MysoreMasalDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(469, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdlyVada)
                    .addComponent(IdlyVadaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MysoreMasalDosa)
                    .addComponent(MysoreMasalDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RavaDosa)
                    .addComponent(RavaDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OnionDosa)
                    .addComponent(OnionDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pongal)
                    .addComponent(PongalQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BREAKFAST", jPanel7);

        jLabel1.setText("DISHES");

        FullMeals.setText("FULL MEALS -Rs 120");
        FullMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullMealsActionPerformed(evt);
            }
        });

        BABYMEALS.setText("BABY MEALSRs 80");
        BABYMEALS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BABYMEALSActionPerformed(evt);
            }
        });

        VegBiriyani.setText("VEG BIRIYANI Rs 90");
        VegBiriyani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegBiriyaniActionPerformed(evt);
            }
        });

        TomatoRice.setText("TOMATO RICE Rs 80");
        TomatoRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TomatoRiceActionPerformed(evt);
            }
        });

        LemonRice.setText("LEMON RICE Rs 60");
        LemonRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LemonRiceActionPerformed(evt);
            }
        });

        jLabel2.setText("QUANTITY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(271, 271, 271)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FullMeals)
                            .addComponent(TomatoRice)
                            .addComponent(LemonRice)
                            .addComponent(VegBiriyani)
                            .addComponent(BABYMEALS))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BabyMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FullMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VegBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TomatoRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LemonRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FullMeals)
                    .addComponent(FullMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BABYMEALS)
                    .addComponent(BabyMealsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VegBiriyani)
                    .addComponent(VegBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TomatoRice)
                    .addComponent(TomatoRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LemonRice)
                    .addComponent(LemonRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LUNCH", jPanel1);

        Uthappam.setText("UTHAPPAM -Rs 50");
        Uthappam.setToolTipText("");
        Uthappam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UthappamActionPerformed(evt);
            }
        });

        jLabel6.setText("DISHES");

        VegNoodles.setText("VEG NOODLES -Rs 100");
        VegNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegNoodlesActionPerformed(evt);
            }
        });

        Dosa.setText("DOSA -Rs 70");
        Dosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosaActionPerformed(evt);
            }
        });

        PanneerRoti.setText("PANNEER ROTI -Rs 90");
        PanneerRoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanneerRotiActionPerformed(evt);
            }
        });

        ChilliParotta.setText("CHILLI PAROTTA -Rs 80");
        ChilliParotta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChilliParottaActionPerformed(evt);
            }
        });

        jLabel7.setText("QUANTITY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VegNoodles)
                            .addComponent(Uthappam)
                            .addComponent(Dosa)
                            .addComponent(PanneerRoti)
                            .addComponent(ChilliParotta))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VegNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UthappamQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanneerRotiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChilliParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Uthappam)
                    .addComponent(UthappamQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VegNoodles)
                    .addComponent(VegNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dosa)
                    .addComponent(DosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanneerRoti)
                    .addComponent(PanneerRotiQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChilliParotta)
                    .addComponent(ChilliParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DINNER", jPanel3);

        Falooda.setText("FALOODA -Rs 170");
        Falooda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaloodaActionPerformed(evt);
            }
        });

        VirginMary.setText("VIRGIN MARY-Rs 65");
        VirginMary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VirginMaryActionPerformed(evt);
            }
        });

        LimeJuice.setText("LIME JUICE -Rs 50");

        jLabel8.setText("DISHES");

        jLabel9.setText("QUANTITY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Falooda)
                            .addComponent(VirginMary)
                            .addComponent(LimeJuice))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VirginMaryQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FaloodaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LimeJuiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Falooda)
                    .addComponent(FaloodaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VirginMary)
                    .addComponent(VirginMaryQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimeJuice)
                    .addComponent(LimeJuiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DESSERTS", jPanel4);

        OrderSum.setColumns(20);
        OrderSum.setRows(5);
        jScrollPane1.setViewportView(OrderSum);

        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });

        jLabel10.setText("DISHES ORDERED WITH THEIR PRICE");

        jButton1.setText("CASH ON DELIVERY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ONLINE PAYMENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TotalButton.setText("TOTAL");
        TotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("APPLY PROMO CODE : ");

        PromoCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromoCodeActionPerformed(evt);
            }
        });

        Apply.setText("APPLY");
        Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(TotalPrice))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(TotalButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Apply)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apply))
                        .addGap(42, 42, 42)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ORDER SUMMARY", jPanel2);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("SABAREESH RESTAURANT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MysoreMasalDosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MysoreMasalDosaActionPerformed
        // TODO add your handling code here:
        
         double quantity = Double.parseDouble(MysoreMasalDosaQuantity.getValue().toString());
         double MysoreMasalDosaprice = 90;
        if(MysoreMasalDosa.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+MysoreMasalDosa.getText()+"; ");
         double price = quantity*MysoreMasalDosaprice;
         OrderSum.append("Quantity :"+MysoreMasalDosaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_MysoreMasalDosaActionPerformed

    private void FaloodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaloodaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(FaloodaQuantity.getValue().toString());
         double Faloodaprice = 170;
        if(Falooda.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Falooda.getText()+"; ");
         double price = quantity*Faloodaprice;
         OrderSum.append("Quantity :"+FaloodaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_FaloodaActionPerformed

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         AddressInfo AI = new AddressInfo();
        AI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IdlyVadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdlyVadaMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_IdlyVadaMouseClicked

    private void IdlyVadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdlyVadaActionPerformed
        // TODO add your handling code here:
       
         double quantity = Double.parseDouble(IdlyVadaQuantity.getValue().toString());
         double IdlyVadaprice = 40;
        if(IdlyVada.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+IdlyVada.getText()+"; ");
         double price = quantity*IdlyVadaprice;
         OrderSum.append("Quantity :"+IdlyVadaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_IdlyVadaActionPerformed

    private void PongalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PongalActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(PongalQuantity.getValue().toString());
         double pongalprice = 70;
        if(Pongal.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Pongal.getText()+"; ");
         double price = quantity*pongalprice;
         OrderSum.append("Quantity :"+PongalQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PongalActionPerformed

    private void RavaDosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RavaDosaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(RavaDosaQuantity.getValue().toString());
         double RavaDosaprice = 60;
        if(RavaDosa.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+RavaDosa.getText()+"; ");
         double price = quantity*RavaDosaprice;
         OrderSum.append("Quantity :"+RavaDosaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_RavaDosaActionPerformed

    private void OnionDosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnionDosaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(OnionDosaQuantity.getValue().toString());
         double OnionDosaprice = 90;
          OrderSum.append("\n"+OnionDosa.getText()+"; ");
            OrderSum.append("Quantity :"+OnionDosaQuantity.getValue()
         +" ;");
        if(OnionDosa.isSelected()){
           // double price = quantity*dosaprice;
        
         double price = quantity*OnionDosaprice;
       
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_OnionDosaActionPerformed

    private void TotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalButtonActionPerformed
        // TODO add your handling code here
       double total_price = 0;
        if(Falooda.isSelected()){
        double quantity = Double.parseDouble(FaloodaQuantity.getValue().toString());
        double Faloodaprice = 170;
        double price = quantity*Faloodaprice;
        total_price = total_price + price;
       }
         if(LimeJuice.isSelected()){
            double quantity = Double.parseDouble(LimeJuiceQuantity.getValue().toString());
            double LimeJuiceprice = 50;
            double price = quantity*LimeJuiceprice;
            total_price = total_price + price;
         }
          if(VirginMary.isSelected()){
            double quantity = Double.parseDouble(VirginMaryQuantity.getValue().toString());
            double VirginMaryprice = 65;
            double price = quantity*VirginMaryprice;
            total_price = total_price + price;
         }
        
        
       if(IdlyVada.isSelected()){
        double quantity = Double.parseDouble(IdlyVadaQuantity.getValue().toString());
        double IdlyVadaprice = 40;
        double price = quantity*IdlyVadaprice;
        total_price = total_price + price;
       }
       if(MysoreMasalDosa.isSelected()){
        double quantity = Double.parseDouble(MysoreMasalDosaQuantity.getValue().toString());
        double MysoreMasalDosaprice = 90;
        double price = quantity*MysoreMasalDosaprice;
        total_price = total_price + price;
       }
        if(RavaDosa.isSelected()){
        double quantity = Double.parseDouble(RavaDosaQuantity.getValue().toString());
        double RavaDosaprice = 60;
        double price = quantity*RavaDosaprice;
        total_price = total_price + price;
       }
         if(OnionDosa.isSelected()){
        double quantity = Double.parseDouble(OnionDosaQuantity.getValue().toString());
        double OnionDosaprice = 90;
        double price = quantity*OnionDosaprice;
        total_price = total_price + price;
       }
          if(Pongal.isSelected()){
        double quantity = Double.parseDouble(PongalQuantity.getValue().toString());
        double Pongalprice = 70;
        double price = quantity*Pongalprice;
        total_price = total_price + price;
       }
          if(FullMeals.isSelected()){
        double quantity = Double.parseDouble(FullMealsQuantity.getValue().toString());
        double FullMealsprice = 120;
        double price = quantity*FullMealsprice;
        total_price = total_price + price;
       }
          if(BABYMEALS.isSelected()){
        double quantity = Double.parseDouble(BabyMealsQuantity.getValue().toString());
        double BabyMealsprice = 80;
        double price = quantity*BabyMealsprice;
        total_price = total_price + price;
       }
         if(VegBiriyani.isSelected()){
        double quantity = Double.parseDouble(VegBiriyaniQuantity.getValue().toString());
        double VegBiriyaniprice = 90;
        double price = quantity*VegBiriyaniprice;
        total_price = total_price + price;
       }
         if(TomatoRice.isSelected()){
        double quantity = Double.parseDouble(TomatoRiceQuantity.getValue().toString());
        double TomatoRiceprice = 80;
        double price = quantity*TomatoRiceprice;
        total_price = total_price + price;
       }
          if(LemonRice.isSelected()){
        double quantity = Double.parseDouble(LemonRiceQuantity.getValue().toString());
        double LemonRiceprice = 60;
        double price = quantity*LemonRiceprice;
        total_price = total_price + price;
       }
           if(Uthappam.isSelected()){
        double quantity = Double.parseDouble(UthappamQuantity.getValue().toString());
        double Uthappamprice = 50;
        double price = quantity*Uthappamprice;
        total_price = total_price + price;
       }
            if(VegNoodles.isSelected()){
        double quantity = Double.parseDouble(VegNoodlesQuantity.getValue().toString());
        double VegNoodlesprice = 100;
        double price = quantity*VegNoodlesprice;
        total_price = total_price + price;
       }
             if(Dosa.isSelected()){
        double quantity = Double.parseDouble(DosaQuantity.getValue().toString());
        double Dosaprice = 70;
        double price = quantity*Dosaprice;
        total_price = total_price + price;
       }
              if(PanneerRoti.isSelected()){
        double quantity = Double.parseDouble(PanneerRotiQuantity.getValue().toString());
        double PanneerRotiprice = 90;
        double price = quantity*PanneerRotiprice;
        total_price = total_price + price;
       }
               if(ChilliParotta.isSelected()){
        double quantity = Double.parseDouble(ChilliParottaQuantity.getValue().toString());
        double ChilliParottaprice = 80;
        double price = quantity*ChilliParottaprice;
        total_price = total_price + price;
       }
                if(Falooda.isSelected()){
        double quantity = Double.parseDouble(FaloodaQuantity.getValue().toString());
        double Faloodaprice = 170;
        double price = quantity*Faloodaprice;
        total_price = total_price + price;
       }
                 if(VirginMary.isSelected()){
        double quantity = Double.parseDouble(VirginMaryQuantity.getValue().toString());
        double VirginMaryprice = 65;
        double price = quantity*VirginMaryprice;
        total_price = total_price + price;
       }
                  if(LimeJuice.isSelected()){
        double quantity = Double.parseDouble(LimeJuiceQuantity.getValue().toString());
        double LimeJuiceprice = 65-15;
        double price = quantity*LimeJuiceprice;
        total_price = total_price + price;
       }
         
       TotalPrice.setText(""+total_price);
          
    }//GEN-LAST:event_TotalButtonActionPerformed

    private void FullMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullMealsActionPerformed
         double quantity = Double.parseDouble(FullMealsQuantity.getValue().toString());
         double FullMealsprice = 120;
        if(FullMeals.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+FullMeals.getText()+"; ");
         double price = quantity*FullMealsprice;
         OrderSum.append("Quantity :"+FullMealsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
           
        }
    }//GEN-LAST:event_FullMealsActionPerformed

    private void BABYMEALSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BABYMEALSActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(BabyMealsQuantity.getValue().toString());
         double BabyMealsprice = 80;
        if(BABYMEALS.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+BABYMEALS.getText()+"; ");
         double price = quantity*BabyMealsprice;
         OrderSum.append("Quantity :"+BabyMealsQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_BABYMEALSActionPerformed

    private void VegBiriyaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegBiriyaniActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(VegBiriyaniQuantity.getValue().toString());
         double VegBiriyaniprice = 90;
        if(VegBiriyani.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+VegBiriyani.getText()+"; ");
         double price = quantity*VegBiriyaniprice;
         OrderSum.append("Quantity :"+VegBiriyaniQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_VegBiriyaniActionPerformed

    private void TomatoRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TomatoRiceActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(TomatoRiceQuantity.getValue().toString());
         double TomatoRiceprice = 80;
        if(TomatoRice.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+TomatoRice.getText()+"; ");
         double price = quantity*TomatoRiceprice;
         OrderSum.append("Quantity :"+TomatoRiceQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_TomatoRiceActionPerformed

    private void LemonRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LemonRiceActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(LemonRiceQuantity.getValue().toString());
         double LemonRiceprice = 60;
        if(LemonRice.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+LemonRice.getText()+"; ");
         double price = quantity*LemonRiceprice;
         OrderSum.append("Quantity :"+LemonRiceQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_LemonRiceActionPerformed

    private void UthappamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UthappamActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(UthappamQuantity.getValue().toString());
         double Uthappamprice = 50;
        if(Uthappam.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Uthappam.getText()+"; ");
         double price = quantity*Uthappamprice;
         OrderSum.append("Quantity :"+UthappamQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_UthappamActionPerformed

    private void VegNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegNoodlesActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(VegNoodlesQuantity.getValue().toString());
         double v_noodlesprice = 100;
        if(VegNoodles.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+VegNoodles.getText()+"; ");
         double price = quantity*v_noodlesprice;
         OrderSum.append("Quantity :"+VegNoodlesQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_VegNoodlesActionPerformed

    private void DosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosaActionPerformed
        // TODO add your handling code here:
         double quantity = Double.parseDouble(DosaQuantity.getValue().toString());
         double Dosaprice = 70;
        if(Dosa.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+Dosa.getText()+"; ");
         double price = quantity*Dosaprice;
         OrderSum.append("Quantity :"+DosaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_DosaActionPerformed

    private void PanneerRotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanneerRotiActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(PanneerRotiQuantity.getValue().toString());
         double PanneerRotiprice = 90;
        if(PanneerRoti.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+PanneerRoti.getText()+"; ");
         double price = quantity*PanneerRotiprice;
         OrderSum.append("Quantity :"+PanneerRotiQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_PanneerRotiActionPerformed

    private void ChilliParottaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChilliParottaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(ChilliParottaQuantity.getValue().toString());
         double ChilliParottaprice = 80;
        if(ChilliParotta.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+ChilliParotta.getText()+"; ");
         double price = quantity*ChilliParottaprice;
         OrderSum.append("Quantity :"+ChilliParottaQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_ChilliParottaActionPerformed

    private void mjn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mjn
        // TODO add your handling code here:
    }//GEN-LAST:event_mjn

    private void PromoCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromoCodeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PromoCodeActionPerformed

    private void ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyActionPerformed
        // TODO add your handling code here:
       JFrame f = new JFrame();
        double Total = Double.parseDouble(TotalPrice.getText());
        if(PromoCode.getText().equals("DIWALI20")){
           double Disc_Amount = Total-(Total*0.3);
           TotalPrice.setText(""+Disc_Amount);
        }
        else{
        JOptionPane.showMessageDialog(f,"Enter a valid code");
        }
        
    }//GEN-LAST:event_ApplyActionPerformed

    private void VirginMaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VirginMaryActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(VirginMaryQuantity.getValue().toString());
         double VirginMaryprice = 80;
        if(VirginMary.isSelected()){
           // double price = quantity*dosaprice;
         OrderSum.append("\n"+VirginMary.getText()+"; ");
         double price = quantity*VirginMaryprice;
         OrderSum.append("Quantity :"+VirginMaryQuantity.getValue()
         +" ;");
         OrderSum.append("Price :"+ price);
            
        }
    }//GEN-LAST:event_VirginMaryActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         OnlinePayment OP = new OnlinePayment();
        OP.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Sabareesh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Sabareesh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Sabareesh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Sabareesh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant_Sabareesh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply;
    private javax.swing.JCheckBox BABYMEALS;
    private javax.swing.JSpinner BabyMealsQuantity;
    private javax.swing.JCheckBox ChilliParotta;
    private javax.swing.JSpinner ChilliParottaQuantity;
    private javax.swing.JCheckBox Dosa;
    private javax.swing.JSpinner DosaQuantity;
    private javax.swing.JCheckBox Falooda;
    private javax.swing.JSpinner FaloodaQuantity;
    private javax.swing.JCheckBox FullMeals;
    private javax.swing.JSpinner FullMealsQuantity;
    private javax.swing.JCheckBox IdlyVada;
    private javax.swing.JSpinner IdlyVadaQuantity;
    private javax.swing.JCheckBox LemonRice;
    private javax.swing.JSpinner LemonRiceQuantity;
    private javax.swing.JCheckBox LimeJuice;
    private javax.swing.JSpinner LimeJuiceQuantity;
    private javax.swing.JCheckBox MysoreMasalDosa;
    private javax.swing.JSpinner MysoreMasalDosaQuantity;
    private javax.swing.JCheckBox OnionDosa;
    private javax.swing.JSpinner OnionDosaQuantity;
    private javax.swing.JTextArea OrderSum;
    private javax.swing.JCheckBox PanneerRoti;
    private javax.swing.JSpinner PanneerRotiQuantity;
    private javax.swing.JCheckBox Pongal;
    private javax.swing.JSpinner PongalQuantity;
    private javax.swing.JTextField PromoCode;
    private javax.swing.JCheckBox RavaDosa;
    private javax.swing.JSpinner RavaDosaQuantity;
    private javax.swing.JCheckBox TomatoRice;
    private javax.swing.JSpinner TomatoRiceQuantity;
    private javax.swing.JButton TotalButton;
    private javax.swing.JTextField TotalPrice;
    private javax.swing.JCheckBox Uthappam;
    private javax.swing.JSpinner UthappamQuantity;
    private javax.swing.JCheckBox VegBiriyani;
    private javax.swing.JSpinner VegBiriyaniQuantity;
    private javax.swing.JCheckBox VegNoodles;
    private javax.swing.JSpinner VegNoodlesQuantity;
    private javax.swing.JCheckBox VirginMary;
    private javax.swing.JSpinner VirginMaryQuantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private String String(int price) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
