/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddelivery;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vasanth
 */
public class Restaurant_Thalappakatti extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant_Anjappar
     */
    public Restaurant_Thalappakatti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ChickenBiriyani = new javax.swing.JCheckBox();
        MuttonBiriyani = new javax.swing.JCheckBox();
        MuttonChukka = new javax.swing.JCheckBox();
        TandooriChicken = new javax.swing.JCheckBox();
        PanneerBiriyani = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        ChickenBiriyaniQuantity = new javax.swing.JSpinner();
        MuttonBiriyaniQuantity = new javax.swing.JSpinner();
        MuttonChukkaQuantity = new javax.swing.JSpinner();
        TandooriChickenQuantity = new javax.swing.JSpinner();
        PanneerBiriyaniQuantity = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        PanneerNoodles = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        EggFriedRice = new javax.swing.JCheckBox();
        BBQchicken = new javax.swing.JCheckBox();
        MuttonDosa = new javax.swing.JCheckBox();
        FriedParotta = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        PannnerNoodlesQuantity = new javax.swing.JSpinner();
        EggFriedRiceQuantity = new javax.swing.JSpinner();
        BBQchickenQuantity = new javax.swing.JSpinner();
        MuttonDosaQuantity = new javax.swing.JSpinner();
        FriedParottaQuantity = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        Jigarthanda = new javax.swing.JCheckBox();
        OreoShake = new javax.swing.JCheckBox();
        LimeJuice = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JigarthandaQuantity = new javax.swing.JSpinner();
        OreoShakeQuantity = new javax.swing.JSpinner();
        LimeJuiceQuantity = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderSum = new javax.swing.JTextArea();
        TotalPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TotalButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PromoCode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mjn(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jLabel4.setText("BREAKFAST NOT PROVIDED BY THE RESTAURANT");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel4)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BREAKFAST", jPanel7);

        jLabel1.setText("DISHES");

        ChickenBiriyani.setText("CHICKEN BIRIYANI -Rs 200");
        ChickenBiriyani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenBiriyaniActionPerformed(evt);
            }
        });

        MuttonBiriyani.setText("MUTTON BIRIYANI Rs 240");
        MuttonBiriyani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuttonBiriyaniActionPerformed(evt);
            }
        });

        MuttonChukka.setText("MUTTON CHUKKA Rs 180");
        MuttonChukka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuttonChukkaActionPerformed(evt);
            }
        });

        TandooriChicken.setText("TANDOORI CHICKEN Rs 420");
        TandooriChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TandooriChickenActionPerformed(evt);
            }
        });

        PanneerBiriyani.setText("PANNEER BIRIYANI Rs 160");
        PanneerBiriyani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanneerBiriyaniActionPerformed(evt);
            }
        });

        jLabel2.setText("QUANTITY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(271, 271, 271)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChickenBiriyani)
                            .addComponent(TandooriChicken)
                            .addComponent(PanneerBiriyani)
                            .addComponent(MuttonChukka)
                            .addComponent(MuttonBiriyani))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MuttonBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChickenBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MuttonChukkaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TandooriChickenQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanneerBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChickenBiriyani)
                    .addComponent(ChickenBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MuttonBiriyani)
                    .addComponent(MuttonBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MuttonChukka)
                    .addComponent(MuttonChukkaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TandooriChicken)
                    .addComponent(TandooriChickenQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanneerBiriyani)
                    .addComponent(PanneerBiriyaniQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LUNCH", jPanel1);

        PanneerNoodles.setText("PANNEER NOODLES -Rs 180");
        PanneerNoodles.setToolTipText("");
        PanneerNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanneerNoodlesActionPerformed(evt);
            }
        });

        jLabel6.setText("DISHES");

        EggFriedRice.setText("EGG FRIED RICE -Rs 120");
        EggFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EggFriedRiceActionPerformed(evt);
            }
        });

        BBQchicken.setText("BBQ CHICKEN (FULL) -Rs 400");
        BBQchicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBQchickenActionPerformed(evt);
            }
        });

        MuttonDosa.setText("MUTTON DOSA -Rs 160");
        MuttonDosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuttonDosaActionPerformed(evt);
            }
        });

        FriedParotta.setText("FRIED PAROTTA -Rs 60");
        FriedParotta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriedParottaActionPerformed(evt);
            }
        });

        jLabel7.setText("QUANTITY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EggFriedRice)
                            .addComponent(PanneerNoodles)
                            .addComponent(BBQchicken)
                            .addComponent(MuttonDosa)
                            .addComponent(FriedParotta))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EggFriedRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PannnerNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BBQchickenQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MuttonDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FriedParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanneerNoodles)
                    .addComponent(PannnerNoodlesQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EggFriedRice)
                    .addComponent(EggFriedRiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBQchicken)
                    .addComponent(BBQchickenQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MuttonDosa)
                    .addComponent(MuttonDosaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FriedParotta)
                    .addComponent(FriedParottaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DINNER", jPanel3);

        Jigarthanda.setText("JIGARTHANDA -Rs 170");
        Jigarthanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JigarthandaActionPerformed(evt);
            }
        });

        OreoShake.setText("OREO SHAKE -Rs 150");
        OreoShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OreoShakeActionPerformed(evt);
            }
        });

        LimeJuice.setText("LIME JUICE -Rs 50");
        LimeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimeJuiceActionPerformed(evt);
            }
        });

        jLabel8.setText("DISHES");

        jLabel9.setText("QUANTITY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jigarthanda)
                            .addComponent(OreoShake)
                            .addComponent(LimeJuice))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OreoShakeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JigarthandaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LimeJuiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(461, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jigarthanda)
                    .addComponent(JigarthandaQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OreoShake)
                    .addComponent(OreoShakeQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimeJuice)
                    .addComponent(LimeJuiceQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DESSERTS", jPanel4);

        OrderSum.setColumns(20);
        OrderSum.setRows(5);
        jScrollPane1.setViewportView(OrderSum);

        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });

        jLabel10.setText("DISHES ORDERED WITH THEIR PRICE");

        jButton1.setText("CASH ON DELIVERY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ONLINE PAYMENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TotalButton.setText("TOTAL");
        TotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("APPLY PROMO CODE");

        jButton3.setText("APPLY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(TotalPrice))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(TotalButton))
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addGap(124, 124, 124))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PromoCode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(62, 62, 62)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ORDER SUMMARY", jPanel2);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("THALAPPAKATTI RESTAURANT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mjn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mjn
        // TODO add your handling code here:
    }//GEN-LAST:event_mjn

    private void TotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalButtonActionPerformed
        // TODO add your handling code here
        double total_price = 0;
       
        if(ChickenBiriyani.isSelected()){
            double quantity = Double.parseDouble(ChickenBiriyaniQuantity.getValue().toString());
            double ChickenBiriyaniprice = 200;
            double price = quantity*ChickenBiriyaniprice;
            total_price = total_price + price;
        }
        if(MuttonBiriyani.isSelected()){
            double quantity = Double.parseDouble(MuttonBiriyaniQuantity.getValue().toString());
            double MuttonBiriyaniprice = 240;
            double price = quantity*MuttonBiriyaniprice;
            total_price = total_price + price;
        }
        if(MuttonChukka.isSelected()){
            double quantity = Double.parseDouble(MuttonChukkaQuantity.getValue().toString());
            double MuttonChukkaprice = 180;
            double price = quantity*MuttonChukkaprice;
            total_price = total_price + price;
        }
        if(TandooriChicken.isSelected()){
            double quantity = Double.parseDouble(TandooriChickenQuantity.getValue().toString());
            double TandooriChickenprice = 420;
            double price = quantity*TandooriChickenprice;
            total_price = total_price + price;
        }
        if(PanneerBiriyani.isSelected()){
            double quantity = Double.parseDouble(PanneerBiriyaniQuantity.getValue().toString());
            double PanneerBiriyaniprice = 160;
            double price = quantity*PanneerBiriyaniprice;
            total_price = total_price + price;
        }
        if(PanneerNoodles.isSelected()){
            double quantity = Double.parseDouble(PannnerNoodlesQuantity.getValue().toString());
            double PanneerNoodlesprice = 180;
            double price = quantity*PanneerNoodlesprice;
            total_price = total_price + price;
        }
        if(EggFriedRice.isSelected()){
            double quantity = Double.parseDouble(EggFriedRiceQuantity.getValue().toString());
            double EggFriedRiceprice = 120;
            double price = quantity*EggFriedRiceprice;
            total_price = total_price + price;
        }
        if(BBQchicken.isSelected()){
            double quantity = Double.parseDouble(BBQchickenQuantity.getValue().toString());
            double BBQchickenprice = 400;
            double price = quantity*BBQchickenprice;
            total_price = total_price + price;
        }
        if(MuttonDosa.isSelected()){
            double quantity = Double.parseDouble(MuttonDosaQuantity.getValue().toString());
            double MuttonDosaprice = 160;
            double price = quantity*MuttonDosaprice;
            total_price = total_price + price;
        }
        if(FriedParotta.isSelected()){
            double quantity = Double.parseDouble(FriedParottaQuantity.getValue().toString());
            double FriedParottaprice = 60;
            double price = quantity*FriedParottaprice;
            total_price = total_price + price;
            
        }
        if(Jigarthanda.isSelected()){
            double quantity = Double.parseDouble(JigarthandaQuantity.getValue().toString());
            double Jigarthandaprice = 170;
            double price = quantity*Jigarthandaprice;
            total_price = total_price + price;
        }
         if(OreoShake.isSelected()){
            double quantity = Double.parseDouble(OreoShakeQuantity.getValue().toString());
            double OreoShakeprice = 150;
            double price = quantity*OreoShakeprice;
            total_price = total_price + price;
         }
         
         
            if(LimeJuice.isSelected()){
            double quantity = Double.parseDouble(LimeJuiceQuantity.getValue().toString());
            double LimeJuiceprice = 50;
            double price = quantity*LimeJuiceprice;
            total_price = total_price + price;
         }
        TotalPrice.setText(""+total_price);

    }//GEN-LAST:event_TotalButtonActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         AddressInfo AI = new AddressInfo();
        AI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceActionPerformed

    private void JigarthandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JigarthandaActionPerformed
        // TODO add your handling code here:
          double quantity = Double.parseDouble(JigarthandaQuantity.getValue().toString());
        double Jigarthandaprice = 170;
        if(Jigarthanda.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+Jigarthanda.getText()+"; ");
            double price = quantity*Jigarthandaprice;
            OrderSum.append("Quantity :"+JigarthandaQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_JigarthandaActionPerformed

    private void FriedParottaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriedParottaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(FriedParottaQuantity.getValue().toString());
        double FriedParottaprice = 60;
        if(FriedParotta.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+FriedParotta.getText()+"; ");
            double price = quantity*FriedParottaprice;
            OrderSum.append("Quantity :"+FriedParottaQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_FriedParottaActionPerformed

    private void MuttonDosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuttonDosaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(MuttonDosaQuantity.getValue().toString());
        double MuttonDosaprice = 160;
        if(MuttonDosa.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+MuttonDosa.getText()+"; ");
            double price = quantity*MuttonDosaprice;
            OrderSum.append("Quantity :"+MuttonDosaQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_MuttonDosaActionPerformed

    private void BBQchickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBQchickenActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(BBQchickenQuantity.getValue().toString());
        double BBQchickenprice = 400;
        if(BBQchicken.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+BBQchicken.getText()+"; ");
            double price = quantity*BBQchickenprice;
            OrderSum.append("Quantity :"+BBQchickenQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_BBQchickenActionPerformed

    private void EggFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EggFriedRiceActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(EggFriedRiceQuantity.getValue().toString());
        double EggFriedRiceprice = 120;
        if(EggFriedRice.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+EggFriedRice.getText()+"; ");
            double price = quantity*EggFriedRiceprice;
            OrderSum.append("Quantity :"+EggFriedRiceQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_EggFriedRiceActionPerformed

    private void PanneerNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanneerNoodlesActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(PannnerNoodlesQuantity.getValue().toString());
        double p_noodlesprice = 180;
        if(PanneerNoodles.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+PanneerNoodles.getText()+"; ");
            double price = quantity*p_noodlesprice;
            OrderSum.append("Quantity :"+PannnerNoodlesQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_PanneerNoodlesActionPerformed

    private void PanneerBiriyaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanneerBiriyaniActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(PanneerBiriyaniQuantity.getValue().toString());
        double PanneerBiriyaniprice = 160;
        if(PanneerBiriyani.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+PanneerBiriyani.getText()+"; ");
            double price = quantity*PanneerBiriyaniprice;
            OrderSum.append("Quantity :"+PanneerBiriyaniQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_PanneerBiriyaniActionPerformed

    private void TandooriChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TandooriChickenActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(TandooriChickenQuantity.getValue().toString());
        double TandooriChickenprice = 420;
        if(TandooriChicken.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+TandooriChicken.getText()+"; ");
            double price = quantity*TandooriChickenprice;
            OrderSum.append("Quantity :"+TandooriChickenQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_TandooriChickenActionPerformed

    private void MuttonChukkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuttonChukkaActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(MuttonChukkaQuantity.getValue().toString());
        double pb_price = 180;
        if(MuttonChukka.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+MuttonChukka.getText()+"; ");
            double price = quantity*pb_price;
            OrderSum.append("Quantity :"+MuttonChukkaQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_MuttonChukkaActionPerformed

    private void MuttonBiriyaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuttonBiriyaniActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(MuttonBiriyaniQuantity.getValue().toString());
        double mb_price = 240;
        if(MuttonBiriyani.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+MuttonBiriyani.getText()+"; ");
            double price = quantity*mb_price;
            OrderSum.append("Quantity :"+MuttonBiriyaniQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_MuttonBiriyaniActionPerformed

    private void ChickenBiriyaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenBiriyaniActionPerformed
        double quantity = Double.parseDouble(ChickenBiriyaniQuantity.getValue().toString());
        double cb_price = 200;
        if(ChickenBiriyani.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+ChickenBiriyani.getText()+"; ");
            double price = quantity*cb_price;
            OrderSum.append("Quantity :"+ChickenBiriyaniQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_ChickenBiriyaniActionPerformed

    private void LimeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimeJuiceActionPerformed
        // TODO add your handling code here:
        double quantity = Double.parseDouble(LimeJuiceQuantity.getValue().toString());
        double LimeJuiceprice = 50;
        if(LimeJuice.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+LimeJuice.getText()+"; ");
            double price = quantity*LimeJuiceprice;
            OrderSum.append("Quantity :"+LimeJuiceQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_LimeJuiceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame();
        double Total = Double.parseDouble(TotalPrice.getText());
        if(PromoCode.getText().equals("DIWALI20")){
           double Disc_Amount = Total-(Total*0.3);
           TotalPrice.setText(""+Disc_Amount);
        }
        else{
        JOptionPane.showMessageDialog(f,"Enter a valid code");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void OreoShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OreoShakeActionPerformed
        // TODO add your handling code here:
          double quantity = Double.parseDouble(OreoShakeQuantity.getValue().toString());
        double OreoShakeprice = 200-50;
        if(OreoShake.isSelected()){
            // double price = quantity*dosaprice;
            OrderSum.append("\n"+OreoShake.getText()+"; ");
            double price = quantity*OreoShakeprice;
            OrderSum.append("Quantity :"+OreoShakeQuantity.getValue()
                +" ;");
            OrderSum.append("Price :"+ price);

        }
    }//GEN-LAST:event_OreoShakeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         OnlinePayment OP = new OnlinePayment();
        OP.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Thalappakatti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Thalappakatti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Thalappakatti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant_Thalappakatti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant_Thalappakatti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BBQchicken;
    private javax.swing.JSpinner BBQchickenQuantity;
    private javax.swing.JCheckBox ChickenBiriyani;
    private javax.swing.JSpinner ChickenBiriyaniQuantity;
    private javax.swing.JCheckBox EggFriedRice;
    private javax.swing.JSpinner EggFriedRiceQuantity;
    private javax.swing.JCheckBox FriedParotta;
    private javax.swing.JSpinner FriedParottaQuantity;
    private javax.swing.JCheckBox Jigarthanda;
    private javax.swing.JSpinner JigarthandaQuantity;
    private javax.swing.JCheckBox LimeJuice;
    private javax.swing.JSpinner LimeJuiceQuantity;
    private javax.swing.JCheckBox MuttonBiriyani;
    private javax.swing.JSpinner MuttonBiriyaniQuantity;
    private javax.swing.JCheckBox MuttonChukka;
    private javax.swing.JSpinner MuttonChukkaQuantity;
    private javax.swing.JCheckBox MuttonDosa;
    private javax.swing.JSpinner MuttonDosaQuantity;
    private javax.swing.JTextArea OrderSum;
    private javax.swing.JCheckBox OreoShake;
    private javax.swing.JSpinner OreoShakeQuantity;
    private javax.swing.JCheckBox PanneerBiriyani;
    private javax.swing.JSpinner PanneerBiriyaniQuantity;
    private javax.swing.JCheckBox PanneerNoodles;
    private javax.swing.JSpinner PannnerNoodlesQuantity;
    private javax.swing.JTextField PromoCode;
    private javax.swing.JCheckBox TandooriChicken;
    private javax.swing.JSpinner TandooriChickenQuantity;
    private javax.swing.JButton TotalButton;
    private javax.swing.JTextField TotalPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private String String(int price) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
